### ISSUE TITLE
Latest snapshots seem to have broken paths in the Python on Windows

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#2811] opened 2024-10-07 03:14 UTC
OpenCOR includes a bunch of tools to help users run Python "stuff", in the snapshots following the 0.7.1 release they no longer seem to work on Windows. This include `jupyternotebook.bat` and all the other scripts that are included.

This is the error I'm getting:

```
C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-08-01-Windows> jupyternotebook.bat
Fatal error in launcher: Unable to create process using '"C:\Users\dave\build\opencor\build\Python\bin\python.exe"  "C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-08-01-Windows\Python\Scripts\jupyter.exe" notebook --ip 127.0.0.1': The system cannot find the file specified.
```

I can't trace things back to anywhere that I'm seeing `C:\Users\dave\build\opencor\build` in any paths, but clearly something internal to the Python installation inside OpenCOR is broken on Windows.

**Comment by agarny** [comment] 2024-10-07 05:55
@dbrnz, I can confirm the issue reported by @nickerso. It looks like our Python upgrade broke things with regards to the shebang? Not sure how this could have happened, but things are clearly broken on Windows (everything is fine on Linux and macOS -- I have just double checked!). My bad for not checking on Windows, thinking that it would just work!

**Comment by dbrnz** [comment] 2024-10-07 08:39
Windows just work? Whatever gave you that idea??

Clearly something is set in the Windows' prebuilt Python plugin that should be cleared and/or updated at install time -- I'll take a look.

**Comment by nickerso** [comment] 2024-10-07 08:56
@dbrnz - just to note that this is with the zip file "installation", not the windows installer. Using the installer requires running those helper scripts with elevated privileges due to the file path editing that happens on first run.

Although to note that with the newer snapshots and the installed version with admin privilege results in the same error with that built in path.

**Comment by agarny** [comment] 2024-10-07 20:32
> Windows just work? Whatever gave you that idea??

Well, you know what I mean (since that part of the code used to work and that we didn't touch it). :)

**Comment by dbrnz** [comment] 2024-10-08 02:57
@agarny I've just rebuilt OpenCOR using the current master/HEAD, using a slightly different Windows build environment -- would you please try the [resulting package](https://www.biosignalml.org/static/downloads/OpenCOR-2024-10-08-Windows.zip). I expect it to fail, given that the Python plugin hasn't been rebuilt, but I'm trying to narrow in on what's broken.

Thanks.

**Comment by agarny** [comment] 2024-10-08 03:18
@dbrnz, I have just given it a try and... nope, still not working:
```
Fatal error in launcher: Unable to create process using '"C:\Users\dave\build\opencor\build\Python\bin\python.exe"  "C:\Users\Alan\Desktop\OpenCOR-2024-10-08-Windows\Python\Scripts\jupyter.exe" notebook --ip 127.0.0.1': The system cannot find the file specified.
```

**Comment by dbrnz** [comment] 2024-10-08 09:52
Hmm, something else has changed in the sense that trying to rebuild the Python plugin fails when packaging it. The first lines of the generated `packagePython.cmake` are:
```
cmake_minimum_required(VERSION 3.14)

# Compress our package

execute_process(COMMAND C:/Program Files/CMake/bin/cmake.exe -E tar -czf C:/Users/dave/build/opencor/build/Python.3.12.2.windows.release.tar.gz bin include lib bin/python.exe Libs/python312.dll Libs/python312.lib Libs/liblzma.dll Libs/sqlite3.dll Libs/libffi-8.dll Libs/libffi-8.lib Libs/liblzma.lib Libs/sqlite3.lib Scripts
                WORKING_DIRECTORY C:/Users/dave/build/opencor/ext/release/Python
                RESULT_VARIABLE RESULT
                OUTPUT_QUIET)
```
Note the missing quotes around `C:/Program Files/CMake/bin/cmake.exe`.

This comes from line 937 of `common.cmake`:
```
# Compress our package

execute_process(COMMAND ${CMAKE_COMMAND} -E tar -czf ${PACKAGE_FILE} ${PACKAGED_FILES}
                WORKING_DIRECTORY ${FULL_LOCAL_EXTERNAL_PACKAGE_DIR}
                RESULT_VARIABLE RESULT
                OUTPUT_QUIET)
```

in which I would expect CMake to automagically quote `${CMAKE_COMMAND}`.

I swear that everything used to **just work**, Windows or otherwise!

**Comment by agarny** [comment] 2024-10-08 10:00
Well, that `execute_process()` call has been like this for at least 7 years (at least the part regarding `${CMAKE_COMMAND}`), so...?!

**Comment by agarny** [comment] 2024-10-08 10:02
It looks like it might be a CMake issue then? I have just checked all of our other `${CMAKE_COMMAND}` uses and none of them uses quotes...

**Comment by dbrnz** [comment] 2024-10-08 10:10
I'll try upgrading my Windows build tools...

**Comment by dbrnz** [comment] 2024-10-08 10:26
Re-installing CMake into C:\CMake got over that particular hurdle -- life was so much easier with 8.3 UPPERCAS.FIL names... :)

**Comment by dbrnz** [comment] 2024-10-08 23:13
I now understand what's going on. The `0.7.1` and earlier releases have `*-script.py` files (e.g. `ipython-script.py`) in `Python\Scripts`, which are intended to wrap the corresponding `*.exe` and make sure paths are correct. These `*-script` files are missing from the Python 3.12 version of OpenCOR.

Next is to remember how these were created -- I recall some script that took an EXE, patched it, and created the `-script` wrapper...

**Comment by dbrnz** [comment] 2024-10-08 23:14
@agarny out of curiosity, what is the path to CMake in your version of Windows? Does it include space characters??

**Comment by agarny** [comment] 2024-10-09 00:13
> @agarny out of curiosity, what is the path to CMake in your version of Windows? Does it include space characters??

Yes, it does: `C:\Program Files\CMake\bin\cmake.exe` (that's the first thing I checked after your previous message yesterday). FWIW, I have just built OpenCOR on Windows. I don't have VS2019 anymore (only use it on GitHub Actions), so I forced the OpenCOR build to use VS2022 and it all compiled fine.

**Comment by agarny** [comment] 2024-10-09 00:26
Interestingly, Windows Security considers the resulting executable to be a threat! If I start it, I get the splash screen and then it stops and I get the Windows Security warning. Windows... 🤯

**Comment by dbrnz** [comment] 2024-10-09 01:45
> Next is to remember how these were created -- I recall some script that took an EXE, patched it, and created the -script wrapper...

It's all there if one looks -- in `PythonPackages/CMakeLists.txt`:

```
# Install the Python package manager and its dependencies
# Note: on Windows, we use our version of pip that is modified to create
#       *-script.py files when installing packages with console scripts, so
#       that they can then be updated to reference OpenCOR's Python
#       executable...
```

Now to sort out `our version of pip...`.

**Comment by agarny** [comment] 2024-10-09 01:57
Man, such a pain... again and again... Sorry!

**Comment by dbrnz** [comment] 2024-10-09 02:23
I had in fact patched the latest `pip` to supposedly support this but there have been significant changes in the way wheels are constructed so something was overlooked. And then, because we knew "Windows would just work", we waited for @nickerso to test things :)

It looks to be only a two line change which is good.

**Comment by dbrnz** [comment] 2024-10-09 04:21
@agarny if you would confirm that [this](https://www.biosignalml.org/static/downloads/OpenCOR-2024-10-09-Windows.zip) now "just works", I'll upload new prebuilt binaries (release and debug) of the Windows' PythonPackages plugin and push changes.

**Comment by agarny** [comment] 2024-10-09 04:43
> @agarny if you would confirm that [this](https://www.biosignalml.org/static/downloads/OpenCOR-2024-10-09-Windows.zip) now "just works", I'll upload new prebuilt binaries (release and debug) of the Windows' PythonPackages plugin and push changes.

Thanks a lot @dbrnz! I have just tested *all* the scripts in your snapshot and they all work as expected. So, as far as I can tell, you fixed things! 🥳

**Comment by nickerso** [comment] 2024-10-09 05:27
in the spirit of testing things, I also grabbed that version and tried it out. While I can now launch a jupyter instance, my notebook is not able to run. I'm getting loads of windows security notifications (things needing to be scanned, which might be causing issues?) and lots of assertion errors on the console I launch the jupyter instance from.

Perhaps less important, in this version the jupyter notebook interface seems to now use the jupyterlab...but maybe that is just a consequence of the newer python.

**Comment by nickerso** [comment] 2024-10-09 05:28
For reference, my test notebook is available in https://models.physiomeproject.org/workspace/a1 as `Cardiac Cellular Electrophysiological Modelling.ipynb`

**Comment by agarny** [comment] 2024-10-09 05:51
> in the spirit of testing things, I also grabbed that version and tried it out. While I can now launch a jupyter instance, my notebook is not able to run. I'm getting loads of windows security notifications (things needing to be scanned, which might be causing issues?) and lots of assertion errors on the console I launch the jupyter instance from.

I have just given your Jupyter notebook a try and it all worked fine (I mean, I got some figures and no errors!) except for Figure 11 for which I got the following errors:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\IPython\core\formatters.py:340, in BaseFormatter.__call__(self, obj)
    338     pass
    339 else:
--> 340     return printer(obj)
    341 # Finally look for special method names
    342 method = get_real_method(obj, self.print_method)

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\IPython\core\pylabtools.py:153, in print_figure(fig, fmt, bbox_inches, base64, **kwargs)
    150     from matplotlib.backend_bases import FigureCanvasBase
    151     FigureCanvasBase(fig)
--> 153 fig.canvas.print_figure(bytes_io, **kw)
    154 data = bytes_io.getvalue()
    155 if fmt == 'svg':

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\backend_bases.py:2164, in FigureCanvasBase.print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2161     # we do this instead of `self.figure.draw_without_rendering`
   2162     # so that we can inject the orientation
   2163     with getattr(renderer, "_draw_disabled", nullcontext)():
-> 2164         self.figure.draw(renderer)
   2165 if bbox_inches:
   2166     if bbox_inches == "tight":

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\artist.py:95, in _finalize_rasterization.<locals>.draw_wrapper(artist, renderer, *args, **kwargs)
     93 @wraps(draw)
     94 def draw_wrapper(artist, renderer, *args, **kwargs):
---> 95     result = draw(artist, renderer, *args, **kwargs)
     96     if renderer._rasterizing:
     97         renderer.stop_rasterizing()

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\artist.py:72, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     69     if artist.get_agg_filter() is not None:
     70         renderer.start_filter()
---> 72     return draw(artist, renderer)
     73 finally:
     74     if artist.get_agg_filter() is not None:

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\figure.py:3154, in Figure.draw(self, renderer)
   3151         # ValueError can occur when resizing a window.
   3153 self.patch.draw(renderer)
-> 3154 mimage._draw_list_compositing_images(
   3155     renderer, self, artists, self.suppressComposite)
   3157 for sfig in self.subfigs:
   3158     sfig.draw(renderer)

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\artist.py:72, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     69     if artist.get_agg_filter() is not None:
     70         renderer.start_filter()
---> 72     return draw(artist, renderer)
     73 finally:
     74     if artist.get_agg_filter() is not None:

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\axes\_base.py:3070, in _AxesBase.draw(self, renderer)
   3067 if artists_rasterized:
   3068     _draw_rasterized(self.figure, artists_rasterized, renderer)
-> 3070 mimage._draw_list_compositing_images(
   3071     renderer, self, artists, self.figure.suppressComposite)
   3073 renderer.close_group('axes')
   3074 self.stale = False

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\image.py:132, in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130 if not_composite or not has_images:
    131     for a in artists:
--> 132         a.draw(renderer)
    133 else:
    134     # Composite any adjacent images together
    135     image_group = []

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\artist.py:72, in allow_rasterization.<locals>.draw_wrapper(artist, renderer)
     69     if artist.get_agg_filter() is not None:
     70         renderer.start_filter()
---> 72     return draw(artist, renderer)
     73 finally:
     74     if artist.get_agg_filter() is not None:

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\axis.py:1387, in Axis.draw(self, renderer, *args, **kwargs)
   1384     return
   1385 renderer.open_group(__name__, gid=self.get_gid())
-> 1387 ticks_to_draw = self._update_ticks()
   1388 tlb1, tlb2 = self._get_ticklabel_bboxes(ticks_to_draw, renderer)
   1390 for tick in ticks_to_draw:

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\axis.py:1275, in Axis._update_ticks(self)
   1270 def _update_ticks(self):
   1271     """
   1272     Update ticks (position and labels) using the current data interval of
   1273     the axes.  Return the list of ticks that will be drawn.
   1274     """
-> 1275     major_locs = self.get_majorticklocs()
   1276     major_labels = self.major.formatter.format_ticks(major_locs)
   1277     major_ticks = self.get_major_ticks(len(major_locs))

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\axis.py:1495, in Axis.get_majorticklocs(self)
   1493 def get_majorticklocs(self):
   1494     """Return this Axis' major tick locations in data coordinates."""
-> 1495     return self.major.locator()

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\ticker.py:2140, in MaxNLocator.__call__(self)
   2138 def __call__(self):
   2139     vmin, vmax = self.axis.get_view_interval()
-> 2140     return self.tick_values(vmin, vmax)

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\ticker.py:2148, in MaxNLocator.tick_values(self, vmin, vmax)
   2145     vmin = -vmax
   2146 vmin, vmax = mtransforms.nonsingular(
   2147     vmin, vmax, expander=1e-13, tiny=1e-14)
-> 2148 locs = self._raw_ticks(vmin, vmax)
   2150 prune = self._prune
   2151 if prune == 'lower':

File ~\Desktop\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\matplotlib\ticker.py:2112, in MaxNLocator._raw_ticks(self, vmin, vmax)
   2109     large_steps = large_steps & (floored_vmaxs >= _vmax)
   2111 # Find index of smallest large step
-> 2112 istep = np.nonzero(large_steps)[0][0]
   2114 # Start at smallest of the steps greater than the raw step, and check
   2115 # if it provides enough ticks. If not, work backwards through
   2116 # smaller steps until one is found that provides enough ticks.
   2117 for step in steps[:istep+1][::-1]:

IndexError: index 0 is out of bounds for axis 0 with size 0
<Figure size 800x400 with 1 Axes>
```

> Perhaps less important, in this version the jupyter notebook interface seems to now use the jupyterlab...but maybe that is just a consequence of the newer python.

Puzzling! I am definitely getting the Jupyter Notebook interface when running `jupyternotebook.bat` and the Jupyter Lab interface when running `jupyterlab.bat`:

**Jupyter Notebook:**

![image](https://github.com/user-attachments/assets/df4beceb-ba00-409b-afbc-ddfe203be1d2)

**Jupyter Lab:**

![image](https://github.com/user-attachments/assets/70fb2c62-c935-4e47-90f9-d5f00ff99717)

**Comment by agarny** [comment] 2024-10-09 05:54
@dbrnz / @nickerso: I will be waiting for confirmation from the two of you that you are happy for PR #2812 to be merged in.

**Comment by nickerso** [comment] 2024-10-09 07:59
> I have just given your Jupyter notebook a try and it all worked fine (I mean, I got some figures and no errors!)

interesting. Did you re-run things or is it just looking at the cached results? If you clear all output and re-run all cells what happens? For me even the initial `import opencor` doesn't run.

**Comment by dbrnz** [comment] 2024-10-09 08:32
I've just tried the notebook under Windows using that snapshot, and:
1. Jupyter notebook does run a notebook and not JupyterLab.
2. Cells run just fine, up to and including plotting figure 4 and closing its simulations.
3. Cells run for figures 5 through to 8 except the resulting plots are very, very wrong -- they are all variants of the following.
4. The kernel crashes, with no error trace, when running the simulation for figure 9.

Why are three different systems all behaving in different ways??

<img width="886" alt="Screenshot 2024-10-09 at 9 23 32 PM" src="https://github.com/user-attachments/assets/77675513-cbfb-4911-a543-831d7d8ddb3b">

**Comment by dbrnz** [comment] 2024-10-09 08:37
Should this behaviour not be a new issue, as the broken paths are fixed...

**Comment by nickerso** [comment] 2024-10-09 09:51
for me I get a continual stream of these while running the new version
![image](https://github.com/user-attachments/assets/ae486589-f56f-4ecb-973b-56c83116bf3b)

I can launch the notebook server and load the notebook, but when trying to execute the first cell
```py
import opencor as opencor
from matplotlib import pyplot as plt
%matplotlib inline
```
it never completes and the console is showing
```
[I 2024-10-09 22:41:16.141 ServerApp] Kernel started: 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:16.152 ServerApp] Timeout waiting for kernel_info reply from 867f57b8-c305-4c5e-8453-d5a6ce528408
[I 2024-10-09 22:42:16.152 ServerApp] Connecting to kernel 867f57b8-c305-4c5e-8453-d5a6ce528408.
[W 2024-10-09 22:42:20.739 ServerApp] Nudge: attempt 10 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:25.775 ServerApp] Nudge: attempt 20 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:30.860 ServerApp] Nudge: attempt 30 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:35.900 ServerApp] Nudge: attempt 40 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:41.000 ServerApp] Nudge: attempt 50 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:46.032 ServerApp] Nudge: attempt 60 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:51.077 ServerApp] Nudge: attempt 70 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:42:56.163 ServerApp] Nudge: attempt 80 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:43:01.233 ServerApp] Nudge: attempt 90 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:43:06.267 ServerApp] Nudge: attempt 100 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[W 2024-10-09 22:43:11.344 ServerApp] Nudge: attempt 110 on kernel 867f57b8-c305-4c5e-8453-d5a6ce528408
[I 2024-10-09 22:43:15.195 ServerApp] Saving file at /Cardiac Cellular Electrophysiological Modelling.ipynb
[E 2024-10-09 22:43:16.194 ServerApp] Uncaught exception GET /api/kernels/867f57b8-c305-4c5e-8453-d5a6ce528408/channels?session_id=e1b8a841-bc2d-40f7-955a-f3c10305d737 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/api/kernels/867f57b8-c305-4c5e-8453-d5a6ce528408/channels?session_id=e1b8a841-bc2d-40f7-955a-f3c10305d737', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\tornado\websocket.py", line 940, in _accept_connection
        await open_result
      File "C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\site-packages\jupyter_server\services\kernels\websocket.py", line 75, in open
        await self.connection.connect()
    TimeoutError: Timeout
[W 2024-10-09 22:43:16.231 ServerApp] Replacing stale connection: 867f57b8-c305-4c5e-8453-d5a6ce528408:e1b8a841-bc2d-40f7-955a-f3c10305d737
Exception in callback _chain_future.<locals>._set_state(<Future finished result={}>, <Future at 0x...returned dict>) at C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\asyncio\futures.py:381
handle: <Handle _chain_future.<locals>._set_state(<Future finished result={}>, <Future at 0x...returned dict>) at C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\asyncio\futures.py:381>
Traceback (most recent call last):
  File "C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\asyncio\futures.py", line 383, in _set_state
    _copy_future_state(other, future)
  File "C:\Users\dnic019\development\OpenCOR\OpenCOR-2024-10-09-Windows\Python\Lib\asyncio\futures.py", line 353, in _copy_future_state
    assert not dest.done()
AssertionError
[I 2024-10-09 22:43:19.766 ServerApp] Connecting to kernel 867f57b8-c305-4c5e-8453-d5a6ce528408.
```

**Comment by nickerso** [comment] 2024-10-09 09:54
ok...now I'm super confused. I went back to 0.7.1 and running the notebook it took a long time to get started but eventually everything worked as expected. I then run the notebook with this new 2024-10-09 version and I got a couple of errors on starting the notebook server but now its "running" all the cells without error ?! The simulation results being plotted are completely messed up for the most part, but things are at least running...

**Comment by nickerso** [comment] 2024-10-09 09:55
> Should this behaviour not be a new issue, as the broken paths are fixed

yeah, probably :) I can confirm that the original broken path issue is no longer present.

**Comment by agarny** [comment] 2024-10-09 10:10
> > I have just given your Jupyter notebook a try and it all worked fine (I mean, I got some figures and no errors!)
> 
> interesting. Did you re-run things or is it just looking at the cached results? If you clear all output and re-run all cells what happens? For me even the initial `import opencor` doesn't run.

I rerun every single cell.

**Comment by agarny** [comment] 2024-10-09 10:17
Anyway, I have merged in @dbrnz's PR since it does indeed fix the current issue.

**Closed** 2024-10-09 10:16 UTC

**Comment by nickerso** [comment] 2024-10-09 10:56
Once there is an official new snapshot release I can submit bug reports against that if the (other) issue persists.

**Comment by agarny** [comment] 2024-10-09 11:25
> Once there is an official new snapshot release I can submit bug reports against that if the (other) issue persists.

Will release a new snapshot "tomorrow".
