### ISSUE TITLE
Python: provide post-install instructions

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#2205] opened 2019-10-31 01:07 UTC
It is essential that the `setpythonpath` script is run after unarchiving an OpenCOR+Python release, as otherwise the scripts in Python's `./bin` directory (`./Scripts` under Windows) don't contain the correct path to OpenCOR's Python. One symptom of things being wrong is `!pip list` failing when run in the GUI Python console.

A note to this effect should be attached to releases on Github.

Note: the Windows'  installer does the right thing.

**Comment by agarny** [comment] 2019-10-31 07:46
Good point. However, I am not sure we want to rely on the end user running that script upon unzipping or installing OpenCOR. People are bound to forget about it (especially when upgrading from one version/snapshot to another). So, couldn't we have that script run automatically when starting OpenCOR. Surely, it ought to be possible, somehow? (In the same way that we register the OpenCOR URI when starting OpenCOR.) This would also allow for people to move/rename the OpenCOR directory, if they need/want, without having to worry about anything.

I will look into it when I have a minute.

**Comment by agarny** [comment] 2019-10-31 09:59
> Shall I do so and generate a pull request??

Yes, that would be great. Thanks!

**Comment by agarny** [comment] 2019-11-01 03:16
Closing as per PR https://github.com/agarny/opencor/pull/10.

**Closed by agarny** 2019-11-01 03:16 UTC
Labels: Task

**Comment by agarny** [comment] 2019-11-01 04:41
Having merged in PR agarny#10 and rebuilt our Python package, I can confirm that it's all working fine (i.e. our Python scripts' shebang gets properly updated).

I will just do a couple of things:
1. Merge `setpythonpath` into `runjupyter` since it's only used there.
2. Move `runjupyter` and `runpython` out of the OpenCOR home directory since a user should never have to run those scripts directly.

**Comment by dbrnz** [comment] 2019-11-01 05:25
Isn't `runpython` something a user would run? Say renamed as `pythonshell`??

Or since it's just a convenience wrapper for `OpenCOR -c PythonShell`, do we simply remove it and document (for power users) how to run the CLI plugin? And users can `alias python="/path/to/OpenCOR -c PythonShell"` if they want to.

**Comment by agarny** [comment] 2019-11-01 07:03
Hmm, I guess we might keep it, but rename it to `pythonshell` indeed.
