### ISSUE TITLE
Export CellML 1.0 doesn't like .xml extension?

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#746] opened 2015-09-14 04:25 UTC
I load a model with the name `bob.xml` and now when I export that model to CellML 1.0 the save as dialog defaults to the filename `bob_exported.xml`. Clicking the save button I get an error message asking me to change the file name :) If I change the filename to `bob_exported.cellml` then it saves fine.

If the requirement is to have a `.cellml` extension, then the default filename should have a `.cellml`. But obviously I would prefer to be allowed to call my file whatever I want to...

**Comment by nickerso** [comment] 2015-09-14 04:28
hmmmm...perhaps this is a bigger problem, I don't seem to be able to save any file with a `.xml` extension.

**Comment by agarny** [comment] 2015-09-14 13:05
**Regarding your first comment:**

May I ask which version of OpenCOR you are using? If you are using the latest snapshot (i.e. snapshot 2015-09-07) and you are trying to export your model to CellML 1.0 using the suggested file name and this in the folder where your CellML 1.1 model is, then it's 'normal'. Indeed, my recent work on issue #736 introduced a regression, but this has since been fixed (see commit db1f171a663cd729632c77e9b84814df7f576f06).

What is certain is that the requirement is not to have a ```.cellml``` extension. The user can used whatever extension s/he wants, although ```.cellml``` is the 'preferred' extension.

If the problem is different, then it would be good to have some steps so that I can exactly reproduce your problem (e.g. did you use the suggested file name, did you try to save/export in the folder where the original file is, etc.).

**Regarding your second comment:**

I must confess that I am puzzled. Some steps would definitely be useful since, as far as I can tell, this is working fine for me.

**Comment by nickerso** [comment] 2015-09-14 20:49
yes, sorry - forgot to mention using latest snapshot (2015-09-07) 64bit OS X.

Not sure I follow the first response - but I think you are saying that there is a bug in that snapshot which is fixed by db1f171? So I can leave that one and test it again in the next snapshot?

The second comment steps to reproduce:

1. Open a CellML model with a `.xml` extension (say `sin_approximations_import.xml` from the workspace https://models.physiomeproject.org/w/andre/sine
2. In the CellML Text view, add a space at the end of the first line (or anywhere else that is valid), to modify the file.
3. Attempt to save the file.
4. Observe the attached error dialog.

![screen shot 2015-09-15 at 8 47 41 am](https://cloud.githubusercontent.com/assets/811244/9861452/8a84703a-5b86-11e5-87d0-0084f417d384.png)

This same process works fine for models with a `.cellml` extension. Perhaps this is the underlying cause of the problem with the export file name? (although that one I was getting the "Choose another file" error message).

**Comment by agarny** [comment] 2015-09-15 08:46
Yes, try what you did in your first comment with the next snapshot.

Regarding your second comment, I just downloaded the latest exposure from your workspace, and opened the ```sin_approximations_import.xml``` file. Then, I added a space at the very beginning of the file and tried to save it, and I can confirm that I have got a similar dialog box to yours above, and this is 'normal'.

Indeed, you may have hidden the output window (below the editor in the ```CellML Text``` view), but if you make it visible you will see that there is an error in your CellML file. Well, it's an 'error' that is due to the fact that you are using the ```CellML Text``` view, a view that requires some keywords to work properly and, here, you are using ```sin``` as a component name (line 3, column 36) while ```sin``` is used by the ```CellML Text``` view for the sine function. So, that's the reason you cannot save the file, and I am not sure there is much that can be done about it. That's a 'limitation' of the ```CellML Text``` view.

Now, I must confess that it's all working fine if you change the extension to ```.cellml```. I have just tried it by renaming ```sin_approximations_import.xml``` to ```sin_approximations_import.cellml``` and, as expected, I am still getting a similar dialog box to yours above.

**Comment by nickerso** [comment] 2015-09-15 09:35
ha ha ha :) The other model I have been using to test this has a component named `model` which also gives an error which I never see.

Also, how long have those error messages been hidden down the bottom of the text edit window???? That would be a really really really useful feature to have visible by default. Trying to track down those errors with guess-and-check editing is always a big pain at the tutorials we have been running.

Finally, with one of these models I can do a `Save As` and successfully save the model to a `.cellml` (but the extension probably doesn't actually matter), but then once I edit the file I can't save the changes due to the error (with `sin` or `model` component names conflicting with the CellML Text format). So I guess the initial save as is really doing a file copy but then once edits are made the CellML Text format parser is used and that fails.

**Comment by agarny** [comment] 2015-09-15 11:55
That output window has been there since the ```CellML Text``` view has been released, and it is visible by default, so I am not sure what you did to have it hidden... :) In fact, if you don't mind resetting all of your OpenCOR settings (either through the ```Tools``` | ```Reset All``` menu, or from the command line: ```./OpenCOR -r```), and open a CellML file using the ```CellML Text``` view, then you should see that output window.

Well guessed about "Save As..." doing a file copy. This is indeed what it will do if OpenCOR notices that the file hasn't been modified.

Ok, so I take it that this issue has now been 'fixed', so closing (but feel free to reopen it, if you think I missed something).

**Closed by agarny** 2015-09-15 11:55 UTC

**Comment by nickerso** [comment] 2015-10-01 20:07
Just to confirm that this:

    Yes, try what you did in your first comment with the next snapshot.

worked. yay! thanks.

**Comment by agarny** [comment] 2015-10-01 21:57
Phew! :)
