### ISSUE TITLE
no default plot selected in 2016-01-25 snapshot

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#867] opened 2016-01-26 01:15 UTC
It seems that when first going to the simulation view there is no "default" plot selected, but I can still choose to add variables to the plot - which has no affect and produces no error.

I'm actually unable to reproduce this one, so it might have just been an issue with the first run of the new version of OpenCOR....

**Comment by agarny** [comment] 2016-01-26 10:38
I am not sure I understand what you mean by "there is no 'default' plot selected" since this is what you should expect when first going to the Single Cell view.

Otherwise, are you saying that you then created a graph for a simulation, ran the simulation and saw nothing?

Whatever the case, let's wait and see whether you come across that issue again and, more importantly indeed, whether you can reproduce it.

**Comment by nickerso** [comment] 2016-01-26 19:47
just for the record, this is what I did:

1. launched new version of OpenCOR, getting the main window with my previously open models.
2. in the first model that was open, switch from edit to simulation view (which displayed a single graph).
3. right-clicked a state variable and chose to plot against independent variable.
4. surprised to not see the plot displayed in the graphs pane :)
5. Ran the simulation anyway and still saw no graph displayed - more surprise :)
6. Noticed that the single graph did not have the blue "selection" bar down its side.
7. Selected the single graph and then redid everything and it all worked.

I'm wondering if it is something to do with whatever information you are saving that enables a new session of OpenCOR to remember which models were open, etc. If that information had a pointer to a graph or simulation view which has changed in the new way of doing things, that could be the problem. Because it certainly hasn't shown up again no matter what I try...

**Comment by agarny** [comment] 2016-01-27 08:23
Ok, this is much clearer now (e.g. what is a **graph** to you is apparently a **graph panel** to me :)). Anyway, I have just:
 1. Reset my OpenCOR settings using the 2015-11-25 snapshot;
 2. Switched to the ```CellML Text``` view; and
 3. Opened the CellML files that are shipped with OpenCOR and selected the Noble 1962 model (simply because if allows for 'better' looking graphs using the default simulation settings).

At this stage, my copy of OpenCOR looks like as follows, which I believe should be similar to what you had before starting to use the 2016-01-25 snapshot:

![screen shot 2016-01-27 at 08 54 28](https://cloud.githubusercontent.com/assets/602265/12607317/3c5310d0-c4d4-11e5-9f87-384952be00ef.png)

At this stage, I closed OpenCOR and restarted it using the 2016-01-25 snapshot. From there, I followed your steps and:
 - Your steps 3 and 4 worked fine for me, i.e. I do get a graph in the ```Graphs``` panel:

![screen shot 2016-01-27 at 09 07 36](https://cloud.githubusercontent.com/assets/602265/12607469/67272156-c4d5-11e5-9840-e70b27ca6fba.png)

 - Step 5 also worked, i.e. I got the expected trace in the graph panel:

![screen shot 2016-01-27 at 09 09 08](https://cloud.githubusercontent.com/assets/602265/12607484/9e3deb48-c4d5-11e5-8797-a6442af12e6c.png)

In step 6, do you mean the vertical blue bar to the left of the graph panel (i.e. the one we can see just 'below' the ```+``` and ```-``` buttons to add/remove a graph panel in the above screenshot)? If so, it would indeed explain why steps 3 to 5 didn't work for you in the first place. This being said, I don't understand why the graph panel didn't have a vertical blue bar to its left.

What is certain is that the ```Single Cell``` view now remembers things in a slightly different way. For example, before it remembered the number of graph panels to create upon restarting OpenCOR, independent of the CellML files that were opened. Starting from the 2016-01-25, the ```Single Cell``` view now remembers the number of graph panels to create for every CellML file that is (or has been) opened (at some point).

Anyway, I can't seem to be able to reproduce your issue, so I am closing it, but feel free to reopen it if you ever manage to reproduce it.

**Closed by agarny** 2016-01-27 08:23 UTC
