### ISSUE TITLE
CellML tools: segmentation fault when trying to export a CellML to C from the command line

### ISSUE THREAD

**Issue by maxneal** [opencor/opencor#581] opened 2015-03-27 16:33 UTC
Hello,
I have been attempting to run OpenCOR from the command line to generate C-code from a CellML model I created but am met with a segmentation fault. Here is the command I used:

```
./OpenCOR -c CellMLTools::export ./PHN/pandit_hinch_niederer.cellml ./PHN/phn_output.c ./formats/C.xml
```

And the resulting error message is:

```
./OpenCOR: line 3:  4938 Segmentation fault: 11  OpenCOR.app/Contents/MacOS/OpenCOR $*
```

I am using a 64-bit MacBook Pro with OS X Lion (10.7.3).  Thanks.

**Comment by agarny** [comment] 2015-03-27 18:40
Thanks for the report Max. FWIW, I have just tried the following export to C from the command line using the 2015-03-05 snapshot:

```
./OpenCOR -c CellMLTools::export ./models/noble_model_1962.cellml ./noble_model_1962.c ./formats/C.xml
```

As expected, it works fine (I have tried it on Mac OS X 10.7.5, as well as on OS X 10.8.5, 10.9.5 and 10.10.2).

In fact, if there was something fundamentally wrong with the export, we would know since we have a similar test for that kind of export. So, my hunch is that the CellML file you try to export contains something that the CellML API (which is used to do the export) doesn't like. So, if at all possible, it would be nice to have that CellML file so that we can see exactly what is going wrong. Alternatively, a CellML file that also crashes OpenCOR (well, the CellML API, it would seem).

**Comment by agarny** [comment] 2015-10-22 07:40
@maxneal, would it be possible for you to have another look at this issue and my comment above? Alternatively, you can close it, if you think it's not relevant anymore.

**Comment by maxneal** [comment] 2015-10-22 14:37
Alan,

I still get the segmentation fault after running that command in my original note. (I'm now on Lion 10.7.5, btw).

I can send you the file that causes the fault if you like (it loads and runs in OpenCOR 0.4.1).

I've been able to work around this issue, so it's not relevant to me right now. I'll leave it up to you if you want to close the issue.

I believe that I installed a previous version of the CellML API on my machine a while ago - maybe that could that be part of the problem?

**Comment by agarny** [comment] 2015-10-22 14:41
OpenCOR uses its own version of the CellML API, so that shouldn't be the reason for the problem you got. Still, I am curious as why it crashes when exporting your CellML file to C from the command line. So, yes, I would appreciate if you could send me the 'guilty' file.

**Comment by maxneal** [comment] 2015-10-22 14:52
Hi Alan,

Attached is the guilty party.

M

**Comment by agarny** [comment] 2015-10-22 15:21
I get the feeling that you replied to the GitHub issue via email, and I am not sure we can attach files that way. Whatever the case, I can't see the attachment...

**Comment by agarny** [comment] 2015-10-22 15:32
The CellML file discussed here can be retrieved from https://gist.github.com/agarny/adead841b09a061bf478.

**Comment by agarny** [comment] 2015-10-27 09:41
Ok, I have just had a go at exporting your CellML file to C from the command line, and it is indeed working fine using the current development version of OpenCOR. FWIW, I tried it on 10.7.5. I don't know whether you got a chance to try again now that you are on 10.7.5 too, but whatever the case I am closing this issue since I clearly cannot reproduce it.

**Closed by agarny** 2015-10-27 09:41 UTC
