### ISSUE TITLE
Bug Report - Comment Signs /* ... */ Remove Code

### ISSUE THREAD

**Issue by s-galliani** [opencor/opencor#1206] opened 2017-02-03 15:36 UTC
Good afternoon Sirs,

I was working with OpenCor in a Windows 10 environment, and, sadly, I lost part of my work for, what I would call, a bug in the program.

Basically, I used /* and */ to comment a big area of my code because I needed to analyse smaller parts of it and find an error in my equations. Unfortunately, OpenCOR crashed for some unknown reason in Windows, so the program restarted. 

As I opened the file I was working with, the commented code parts between the two /* and */ signs were disappeared. 

This behavior is independent from the crash itself, I checked and it happens even in case I save the file with the commented part in it, close the program and reopen the file. Those parts are simply removed.

I just want to mention this, because it might be helpful to fix it for future releases and point it out somehow to the final user till that point.

I wish you a nice weekend and thanks.

Sincerely yours,

Simona Galliani

**Comment by agarny** [comment] 2017-02-03 15:55
First of all, I am really sorry that you lost part of your work. Hopefully, it will be relatively 'easy' for you to redo what you lost.

Regarding the serialisation of `/* XXX */` comments, I am afraid that this is actually the expected behaviour, as documented [here](http://opencor.ws/user/plugins/editing/CellMLTextView.html#Comments), and I am not sure there is much we can do about it since the serialisation is done using CellML, i.e. an XML-based format (we are open to suggestions though).

As for the crash itself, this is clearly not the expected behaviour, so feel free to create an issue for it if you are ever able to reproduce it.

**Comment by s-galliani** [comment] 2017-02-07 16:19
Hi Alan,

thanks a lot for your kind reply.
I would like to be able to give you any suggestion to solve this
serialization problem, but I am not an expert though, and I really have any
clue from xml coding point of view.

It could help to have a "Comment/Uncomment" function that can allow the
user to comment big code parts, as a possible alternative solution, just to
work it out easily.

That said, the crash in Windows 10 happens by chances, meaning that it
happens either when I click the "Reset Model Parameter" icon or when I
click the "Clear Simulation Data" one.
The debug message is the following: "An unhandled win32 exception occurred
in OpenCOR.exe [9532]." , this is all I can tell you unfortunately. Hope it
can be of any help.

Cheers,

Simona



2017-02-03 16:55 GMT+01:00 Alan Garny <notifications@github.com>:

**Comment by agarny** [comment] 2017-02-07 16:34
> It could help to have a "Comment/Uncomment" function that can allow the
user to comment big code parts, as a possible alternative solution, just to
work it out easily.

There is actually a way to comment/uncomment a big chunk of test. All you need to do is to select the lines you want to comment/uncomment and press `Ctrl+/`. For example, if you open the `van_der_pol_model_1928.cellml` model (that is shipped with OpenCOR), then you will get the following in the `CellML Text` view:

```
def model van_der_pol_model_1928 as
    def comp main as
        def unit per_second as
            unit second {expo: -1};
        enddef;

        var time: second;
        var x: dimensionless {init: -2};
        var y: dimensionless {init: 0};
        var epsilon: dimensionless {init: 1};

        ode(x, time) = y*1{per_second};
        ode(y, time) = (epsilon*(1{dimensionless}-sqr(x))*y-x)*1{per_second};
    enddef;
enddef;
```

Now, say that you want to comment out all the variable declarations. You could then double click on the line that defines the `time` variable and then move your mouse down to the line that defines the `epsilon` variable. You will see that 4 lines are fully selected (and they must be fully selected for things to work). From there, all you need to do is press `Ctrl+/` and you will get:

```
def model van_der_pol_model_1928 as
    def comp main as
        def unit per_second as
            unit second {expo: -1};
        enddef;

//        var time: second;
//        var x: dimensionless {init: -2};
//        var y: dimensionless {init: 0};
//        var epsilon: dimensionless {init: 1};

        ode(x, time) = y*1{per_second};
        ode(y, time) = (epsilon*(1{dimensionless}-sqr(x))*y-x)*1{per_second};
    enddef;
enddef;
```

If you then save the file and reload it, you will get:

```
def model van_der_pol_model_1928 as
    def comp main as
        def unit per_second as
            unit second {expo: -1};
        enddef;

        //        var time: second;
        //        var x: dimensionless {init: -2};
        //        var y: dimensionless {init: 0};
        //        var epsilon: dimensionless {init: 1};

        ode(x, time) = y*1{per_second};
        ode(y, time) = (epsilon*(1{dimensionless}-sqr(x))*y-x)*1{per_second};
    enddef;
enddef;
```

This is the way it gets rendered back (due to the fact that we are using XML underneath).

> That said, the crash in Windows 10 happens by chances, meaning that it happens either when I click the "Reset Model Parameter" icon or when I click the "Clear Simulation Data" one.
> The debug message is the following: "An unhandled win32 exception occurred in OpenCOR.exe [9532]." , this is all I can tell you unfortunately. Hope it can be of any help.

I am afraid that it doesn't help much. Is that something that always happens with the same model or does it happen with any model? If it only happens with a certain model, then it would be nice if you could email it to me.

**Comment by agarny** [comment] 2017-03-03 18:34
This was not a bug in the first place, so closing.

**Closed by agarny** 2017-03-03 18:34 UTC

**Comment by dbrnz** [comment] 2017-03-03 20:53
@agarny, why isn't it straight forward to translate between `/* ... */` and `<!-- ... -->`?

**Comment by agarny** [comment] 2017-03-03 21:16
@dbrnz: have a look at http://opencor.ws/user/plugins/editing/CellMLTextView.html#Comments. There, I mention a couple of cases that I think would be difficult, if not impossible, to serialise back. In fact, when you think that `// XXX` comments are already not a 1-1 conversion (see above), `/* XXX */` can only be worse since they offer more flexibility to the user.

I remember that, when I was working on this, I wanted to be able to serialise back `/* XXX */` comments, but then the more I was thinking about it the more difficult, if not impossible, cases I could think of.

Now, it may very well be that I tackled this problem from the wrong angle, so feel free to make suggestions. I, for one, would love to be able to have a 100% 1-1 conversion for `// XXX` and `/* XXX */` comments.
