### ISSUE TITLE
Single Cell view: rename it to something more appropriate?

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#567] opened 2015-03-07 10:47 UTC
The name "Single Cell" is quite confusing and really has nothing to do with the purpose of the view. A possible name might be "Model Simulation".

**Comment by nickerso** [comment] 2015-03-07 10:48
I should add that this is not meant to be something done any time soon, just flagging it as something to consider one rainy day in the future...

**Comment by agarny** [comment] 2015-03-07 11:01
I agree that the name is not that great. However, at some point, I would like to be able to run (simple) multi-cellular simuations in OpenCOR, hence the name of ```Single Cell``` for the current simulation view.

Otherwise, to have ```Model Simulation``` as a name for the view would be slightly redundant since that view is part of the ```Simulation``` mode.

**Comment by agarny** [comment] 2017-04-05 07:15
Duplicate of issue #1256, so closing.

**Closed by agarny** 2017-04-05 07:15 UTC
