### ISSUE TITLE
libCellML cannot be imported with OpenCOR

### ISSUE THREAD

**Issue by jonrkarr** [opencor/opencor#2485] opened 2021-05-31 21:15 UTC
I noticed this issue with the OpenCOR Docker image. I'm posting this here because I suspect the origin of the issue is OpenCOR's dynamic use of Python.

### Steps to reproduce
Attempting to import libCellML into the OpenCOR Docker image produces the linking error below.
```sh
opencor/opencor:2021-05-19
docker run -it --rm \
    --entrypoint bash \
    opencor/opencor:2021-05-19 \
    -c "/home/opencor/OpenCOR/python/bin/python -m pip install libcellml; /home/opencor/OpenCOR/python/bin/python -c \"import libcellml\""
```

### Result
```sh    
Collecting libcellml
  Downloading libcellml-0.2.0.dev21-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 30.6 MB/s 
Installing collected packages: libcellml
Successfully installed libcellml-0.2.0.dev21
WARNING: You are using pip version 20.3.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/opencor/OpenCOR/python/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/opencor/OpenCOR/python/lib/python3.7/site-packages/libcellml/__init__.py", line 12, in <module>
    from libcellml.analyser import Analyser
  File "/home/opencor/OpenCOR/python/lib/python3.7/site-packages/libcellml/analyser.py", line 13, in <module>
    from . import _analyser
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

## Second example
The same error occurs when trying to import libCellML into OpenCOR's Python shell
```sh
docker run -it --rm \
    --entrypoint bash \
    opencor/opencor:2021-05-19 \
    -c "/home/opencor/OpenCOR/python/bin/python -m pip install libcellml; OpenCOR -c PythonShell -c \"import libcellml\""
```

**Comment by agarny** [comment] 2021-06-05 02:57
I just had a quick look at this using the 2021-05-19 snapshot of OpenCOR on Ubuntu 20.04 (i.e. directly as opposed to through Docker) and I can indeed confirm the issue. However, I don't think this is an issue with OpenCOR. Indeed:
 - I can, for instance and using OpenCOR's Python, `pip install` and `import` pandas just fine; and
 - I installed Python 3.7(.10) (since OpenCOR comes with Python 3.7(.5)) on my Ubuntu 20.04 virtual machine and although I can `pip install` it fine, I get the same error when `import`ing it:
```bash
(test_3_7) $ python               
Python 3.7.10 (default, May  3 2021, 02:44:43) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcellml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alan/venv/test_3_7/lib/python3.7/site-packages/libcellml/__init__.py", line 12, in <module>
    from libcellml.analyser import Analyser
  File "/home/alan/venv/test_3_7/lib/python3.7/site-packages/libcellml/analyser.py", line 13, in <module>
    from . import _analyser
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

@hsorby, any idea what might be going wrong here?

Also, @hsorby, why do we have a Python 3.7 package for libCellML on Linux, but not on Windows and macOS? Indeed, I wanted to check libCellML using OpenCOR's Python on macOS but, not surprisingly, I can't.

**Comment by jonrkarr** [comment] 2021-06-05 04:11
This issue was unclear to me too. 

Here's another data point: libcellml works fine in my Python environment with Python 3.7.5 and Python 3.9.4.

I posted this here rather than to the libcellml repo because my best guess is that this is a quirk of the particular Python environment that is being used to distribute OpenCOR. Despite several attempts, I could figure out how to get python to figure libpython3.7m.so.1.0 although it is present in the Python environment that OpenCOR distributes.

**Comment by agarny** [comment] 2021-06-05 04:33
> Here's another data point: libcellml works fine in my Python environment with Python 3.7.5 and Python 3.9.4.

Python 3.7.5 on Linux? Which distribution? It certainly didn't work for me on Ubuntu 20.04 using Python 3.7.10.

> I posted this here rather than to the libcellml repo because my best guess is that this is a quirk of the particular Python environment that is being used to distribute OpenCOR. Despite several attempts, I could figure out how to get python to figure libpython3.7m.so.1.0 although it is present in the Python environment that OpenCOR distributes.

I am happy to accept that there might be something wrong with OpenCOR's Python environment (@dbrnz, any views on that?), but then why would a package like pandas work fine? Also, I know people who have installed other Python packages just fine. Anyway, let's see what @hsorby has to say about this.

**Comment by jonrkarr** [comment] 2021-06-05 04:53
I used Mint 19.2 (Ubtunu 18.04.5), Python 3.7.5, and libCellML 0.2.0.dev21. 

In Docker images, I also have libCellML running in Ubuntu (20 I think) and Python 3.9.5.

This issue puzzled me. It could very well be an issue with the compilation of libCellML.

This issue doesn't affect what we're trying to do since libCellML is for CellML 2 and the existing models are for 1. I thought you would probably want to know be aware of this.

**Comment by agarny** [comment] 2021-06-05 19:56
> This issue doesn't affect what we're trying to do since libCellML is for CellML 2 and the existing models are for 1. I thought you would probably want to know be aware of this.

Yes, we definitely want and need to be made aware of issues like this.

**Comment by dbrnz** [comment] 2021-06-05 21:11
`libcellml` works fine with the 2020-06-19 release of OpenCOR under Ubuntu 18.04.

Given that Python 3.7.10 under Ubuntu 20.04 also fails the reason is outside of OpenCOR  --  I'm guessing there is something about how libcellml is packaged that causes problems for both OpenCOR and Python 3.7.10 under Ubuntu 20.04.

Hmm, I'm wondering if not being able to find libpython is a similar issue to the one with DSOs not being able to find symbols (see commit b6fc911), although it more looks as if either the path to libpython, or the global library search path, in libcellml's library is not properly set. @hsorby ??

**Comment by hsorby** [comment] 2021-06-06 08:19
I think the reason is possibly quite simple, libCellML is built against Python 3.7.9 on GNU/Linux.  I will try to modify the release build script of libCellML to use Python 3.7.10 and see if this is indeed the problem.

**Comment by dbrnz** [comment] 2021-06-06 10:18
Hmm, a minor Python version change shouldn't break a binary package...

**Comment by agarny** [comment] 2021-06-06 20:20
Like @dbrnz, I wouldn't expect a patch (not minor) version change to break a Python package. Also, for @jonrkarr, libCellML works fine with Python 3.7.5 (the version used by OpenCOR) on Mint 19.2.

**Comment by dbrnz** [comment] 2021-06-07 08:33
Looking closer at this, I see:
```
$ ldd python/lib/python3.7/site-packages/libcellml/_analyser.so
	linux-vdso.so.1 (0x00007ffd52c7e000)
	libcellml.so.0.2.0-dev.21 => /home/dave/build/OpenCOR-2021-05-19-Linux/python/lib/python3.7/site-packages/libcellml/libcellml.so.0.2.0-dev.21 (0x00007ff249e74000)
	libpython3.7m.so.1.0 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff249e5d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff249e3a000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff249c59000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff249b08000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff249aed000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff2498fb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff24a242000)
```
and yet in OpenCOR's Python we have:
```
$ ls -l python/lib/
total 4948
-rw-r--r--  1 dave dave   74848 May 19 17:39 libbz2.so
-rw-r--r--  1 dave dave  162264 May 19 17:39 liblzma.so
-rw-r--r--  1 dave dave 3607264 May 19 17:39 libpython3.7m.so
-rw-r--r--  1 dave dave 1212216 May 19 17:39 libsqlite3.so
drwxrwxr-x 35 dave dave    4096 May 19 17:43 python3.7
```

In other words `libcellml` is looking for `libpython3.7m.so.1.0` yet OpenCOR provides `libpython3.7m.so`.

Things can be made to work by creating a symbolic link for `libpython3.7m.so.1.0` and setting `LD_LIBRARY_PATH` to OpenCOR's `python/lib` directory.

```
$ python/bin/python
Python 3.7.5 (default, Dec 11 2020, 14:03:40)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from libcellml.analyser import Analyser
>>>
```

LD_LIBRARY_PATH is needed because our libpython is not in the standard places Linux looks for libraries -- see section 3.9 of [dsohowto.pdf](https://akkadia.org/drepper/dsohowto.pdf).

**Comment by dbrnz** [comment] 2021-06-07 10:52
Why then do I have `libcellml` working with the 2020-06-19 release of OpenCOR under Ubuntu 18.04? Because the system loader has managed to find a `libpython3.7m.so.1.0` on the default library search path:
```
$ ldd /home/dave/build/OpenCOR-2020-06-19-Linux/python/lib/python3.7/site-packages/libcellml/_analyser.so
	linux-vdso.so.1 (0x00007ffcc11e4000)
	libcellml.so.0.2.0-dev.21 => /home/dave/build/OpenCOR-2020-06-19-Linux/python/lib/python3.7/site-packages/libcellml/libcellml.so.0.2.0-dev.21 (0x00007f20d9da0000)
	libpython3.7m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0 (0x00007f20d967b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f20d9477000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f20d9258000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f20d8ecf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f20d8b31000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f20d8919000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f20d8528000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f20d82f6000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f20d80d9000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f20d7ed6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f20da158000)
```
The only thing is that it is not the `libpython` provided by OpenCOR...

I'm thinking we need to do the following:
1. Apply the appropriate naming convention for Linux shared objects when naming `libpython` in OpenCOR, creating symbolic links when needed.
2. Make sure `libcellml` uses a general enough name  when referring to `libpython` (why is `libpython3.7m.so.1.0` used and not `libpython3.7m.so`??).
3. Have OpenCOR set `LD_LIBRARY_PATH` to our Python's `./lib` directory, both in the helper scripts used to start Python/IPython/Jupyter, and when initialising its Python plugin.

Then all should be well!

**Comment by agarny** [comment] 2021-06-07 11:01
Thanks for your detective work @dbrnz. I can confirm that things can indeed be made to work the way you describe, although I am definitely not a fan of `LD_LIBRARY_PATH`. At this stage, I would definitely be in favour of making sure that libCellML references `libpython3.7m.so` rather than `libpython3.7m.so.1.0`, not least because this is what I would expect by default. @hsorby?

**Comment by dbrnz** [comment] 2021-06-07 11:37
I also would rather we didn't have to set `LD_LIBRARY_PATH` but unless we start requiring `sudo` for OpenCOR installation so as to add a configuration file to `/etc/ld.so.conf.d/` and run `ldconfig` we may have little choice.

However this isn't just an OpenCOR issue. Looking at Python3.7 under Ubuntu 20.04 (this is the PPA distribution) we have:
```
$ ldd /usr/bin/python3.7
	linux-vdso.so.1 (0x00007ffd9b5f3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb05b7d7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb05b7d1000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb05b7cc000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb05b79e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb05b782000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb05b633000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb05b43f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb05bd6b000)
```
which makes me think that `libpython` has been statically linked.  `libcellml` fails simply because `libpython3.7m.so` hasn't been provided -- searching the system finds no such file (apart from OpenCOR's).

Compare this with OpenCOR's Python, where we dynamically link:
```
$ ldd bin/python3.7
	linux-vdso.so.1 (0x00007fff3c59e000)
	libpython3.7m.so => /home/dave/build/OpenCOR-2021-05-19-Linux/python/bin/../lib/libpython3.7m.so (0x00007f896edad000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f896ebaa000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f896ea5b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f896ea55000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f896ea32000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f896ea2d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f896f12d000)
```

Is the real solution to statically link `libpython` into `libcellml`? I suspect this is what is done in other Python packages that use wrapped C/C++ code. In fact checking `.so` files bundled with both `numpy` and `scipy` find no references to `libpython`. Back to @hsorby...

**Comment by agarny** [comment] 2021-06-07 11:46
> At this stage, I would definitely be in favour of making sure that libCellML references `libpython3.7m.so` rather than `libpython3.7m.so.1.0`, not least because this is what I would expect by default. @hsorby?

I take it back since this would still require setting `LD_LIBRARY_PATH`.

> Is the real solution to statically link `libpython` into `libcellml`? I suspect this is what is done in other Python packages that use wrapped C/C++ code. In fact checking `.so` files bundled with both `numpy` and `scipy` find no references to `libpython`. Back to @hsorby...

I also noticed that with `numpy` and `scipy` and, in fact, with all the Python packages that we ship. So, yes, my vote would also be with to statically linking `libpython` into `libcellml`.

**Comment by dbrnz** [comment] 2021-06-07 11:56
> So, yes, my vote would also be with to statically linking `libpython` into `libcellml`.

Which would also ensure that `libcellml` works with non-system Python installations (e.g. Python 3.7 on Ubuntu 20.04).

**Comment by agarny** [comment] 2021-06-07 20:53
> > So, yes, my vote would also be with to statically linking `libpython` into `libcellml`.
> 
> Which would also ensure that `libcellml` works with non-system Python installations (e.g. Python 3.7 on Ubuntu 20.04).

Indeed, I was going to make that exact same comment.

**Comment by agarny** [comment] 2021-06-07 23:33
Ok, we discussed this issue at our weekly libCellML meeting. Bottom line: libCellML won't statically link `libpython`. :/

libCellML's documentation is going to be updated to make it clear that Python 3.7's shared libraries should be installed on versions of Linux that don't natively come with Python 3.7. In other words, on Ubuntu 20.04, one would need to install Python 3.7 as follows:
```bash
sudo add-apt-repository ppa:deadsnakes/ppa       
sudo apt update    
sudo apt install python3.7 libpython3.7
```
From there, libCellML can be `pip install`ed and `import libcellml` works fine... including in OpenCOR's Python. So, that is it for this libCellML-specific issue, so closing it (unless I missed something in which case feel free to reopen it).

**Closed by agarny** 2021-06-07 23:33 UTC
