### ISSUE TITLE
OpenCOR crashes due to a wrong assignment using Python

### ISSUE THREAD

**Issue by WeiweiAi** [opencor/opencor#2526] opened 2021-08-10 03:44 UTC
Basic info: Window 10, OpenCOR Snapshot 2021-05-19

Description: 
The crash is caused by a mistake of assignment using Python. It has nothing to do with any particular model.  
Here is an example of a Python script:
```python
import opencor as oc

# Load the simulation file
simfile='anyfile.sedml'
simulation = oc.open_simulation(simfile)

# The data object houses all the relevant information
# and pointers to the OpenCOR internal data representations
data = simulation.data()
# Modify the initial value of some state variabls and run the simulation
V_initial = [0]
data.states()['outputs/V'] = V_initial  ##[Here is a mistake]
simulation.run()
# Access simulation results
results = simulation.results()
...
```
The OpenCOR crashes whenever running the above Python script. 
There is a mistake in the example, and it is supposed to be
```python
data.states()['outputs/V'] = V_initial [0]
```
or 
```python
V_initial = 0
data.states()['outputs/V'] = V_initial
```
After the correction, the simulation works fine.
It would be good if the OpenCOR throws an error instead of crashing when encountering the error like in the example.
Thanks.

**Comment by agarny** [comment] 2021-08-10 05:06
Thanks for the report @WeiweiAi. It would be nice if you could provide me with whatever files are known to reproduce the problem. It will not only save me time while working on your issue, but also if I ever need to come back to this issue.

**Comment by WeiweiAi** [comment] 2021-08-10 05:22
Hi Alan,

You could clone this workspace
https://models.physiomeproject.org/workspace/64f to the local machine.
There is a file  "originalFig12_sim.py" under the folder sed-ml.  You could
modify line 40 as below :
original line 40: data.states()['outputs/V'] = iV_initial
Change line 40 to: data.states()['outputs/V'] = V_initial

Save the modification and in the OpenCOR Python console:

     In [1]: cd path/to/folder_this_file_is_in
     In [2]: run originalFig12_sim.py

It should reproduce the problem.

Thanks.

Best regards,
Weiwei

**Comment by agarny** [comment] 2021-08-10 05:39
This is not working for me. Your workspace has been cloned to `/Users/Alan/Desktop/64f`. So, from the OpenCOR's Python Console window, I did:
```python
cd /Users/Alan/Desktop/64f/sed-ml
run originalFig12_sim.py
```
which results in:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Desktop/64f/sed-ml/originalFig12_sim.py in <module>
     15 # Load the simulation file
     16 simfile='periodic-stimulus.sedml'
---> 17 simulation = oc.open_simulation(simfile)
     18 
     19 # The data object houses all the relevant information

ValueError: Error: the imports could not be fully instantiated (&lt;strong&gt;/Users/Alan/Desktop/64f/experiments/&lt;/strong&gt; imports &lt;strong&gt;../cellLib/Components/units.cellml&lt;/strong&gt;, which contents could not be retrieved).
```

From there, I tried to run the script from the command line (the preferred option for me):
```bash
cd /Users/Alan/Desktop/64f/sed-ml
[PathToOpenCOR]/pythonshell originalFig12_sim.py
```
and I am getting a crash... but I am getting a crash with your both your original script and the modified one.

So, at this stage, I can't reproduce your problem.

**Comment by agarny** [comment] 2021-08-10 06:22
FTR, the problem was that the workspace contains a Git submodule which wasn't initialised. Once initialised, I can reproduce the problem as described by @WeiweiAi. Now, the question is whether we can catch a Python "error" and thus prevent OpenCOR from crashing...

**Comment by dbrnz** [comment] 2021-08-10 08:58
> Now, the question is whether we can catch a Python "error" and thus prevent OpenCOR from crashing...

AFAIK we do check for Python errors and respond appropriately...

I'm guessing that the underlying fault will be in a wrapper around one of our OpenCOR classes. In particular I understand the crash happens with:
```
V_initial = [0]
data.states()['outputs/V'] = V_initial
```
which is when a `list` is assigned into the `states` array instead of an expected `number`. @agarny, I'm happy to take a look if you would like me to.

**Comment by agarny** [comment] 2021-08-10 10:46
Yes, I know exactly where the problem occurs: [here](https://github.com/opencor/opencor/blob/292a04e33e030d3f9a0214982124839ea88b9473/src/plugins/dataStore/DataStore/src/datastorepythonwrapper.cpp#L113). Looking at the code, the obvious fix seems to be [this one](https://github.com/agarny/opencor/commit/ace2035be43fddcb65e73f4dc23f54e2b9ddcefe), which now results in OpenCOR behaving better:
<img width="1694" alt="Screen Shot 2021-08-10 at 22 40 50" src="https://user-images.githubusercontent.com/602265/128853381-3214ac14-7e9e-402b-85c5-0ebaad352c12.png">
No idea why the value returned by `PyNumber_Check()` wasn't checked (my fault when I merged your code?). Either way, this now seems fine. Otherwise, I checked whether `PyNumber_Check()` is used in other places and it's not. So, I guess we can consider this issue fixed?

**Comment by dbrnz** [comment] 2021-08-10 10:52
Looks good to close, thanks!

**Comment by agarny** [comment] 2021-08-10 10:53
Great, thanks.

**Closed** 2021-08-10 11:15 UTC
Labels: Python
