### ISSUE TITLE
The desktop icon disappeared again on Ubuntu 16.10

### ISSUE THREAD

**Issue by ssafaei** [opencor/opencor#1235] opened 2017-02-27 21:25 UTC
Same issue as before...

**Comment by agarny** [comment] 2017-02-28 07:05
Argh, this is really annoying since I clearly haven't changed that code recently. Could you please tell me which version last worked for you and which version is currently failing for you (is that the 2017-02-24 snapshot?)?

**Comment by ssafaei** [comment] 2017-02-28 07:42
Yes, 2017-02-24 snapshot fails, but the one before that was working.

**Comment by agarny** [comment] 2017-02-28 09:11
Thanks @ssafaei and sorry again about this. I will have a look and try to get it fixed once and for all.

**Comment by agarny** [comment] 2017-03-01 17:13
FTR, this is 'related' to issue #1147, but not really. Indeed, the problem is that between the 2017-02-10 and 2017-02-24 snapshots, I changed the signature of `Core::exec()` and it now returns the exit code of the program that is executed rather than just `true` or `false` (to determine whether the program executed fine or not). Now, a program that finishes normally will return `0`, so I modified our various calls to `Core::exec()` except the one that is used to check that we can set the application icon (and a few other things) on Linux. Argh! So, yes, my big bad. Sorry @ssafaei!

**Closed** 2017-03-01 17:15 UTC
