### ISSUE TITLE
Unrecognised CellML when loading models on a Windows 7 Enterprise machine

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#1382] opened 2017-07-26 05:59 UTC
At a recent tutorial we had one participant who was unable to load any CellML files into OpenCOR: 21 June 2017 snapshot, windows 7 enterprise service pack 1.

Any attempt to load (valid) CellML documents from local files or the repository resulted in the CellML Text and Raw CellML editors saying they were unable to open those types of files, the Raw Text view would should the perfectly valid CellML document. SED-ML documents could be loaded, but then they wouldn't execute due to being unable to load the CellML model.

We could create a new CellML model, and that worked fine. It could be saved and we could switch between the Raw CellML and the CellML Text views, but once it was closed the model could not be reopened.

**Comment by nickerso** [comment] 2017-07-26 05:59
I'm guessing this might be the CellML API not playing nice when trying to load documents on this platform?

**Comment by agarny** [comment] 2017-07-31 12:41
I am not sure it is an issue related to the CellML API. I use Windows 7 SP1 for my Windows tests and I must confess that I have never come across that problem. It would be interesting to be able to reproduce it.

**Comment by agarny** [comment] 2018-12-18 21:54
Closing this as we were never able to reproduce this problem locally, not to mention that OpenCOR has evolved a lot since so it might not be relevant anymore. If it is, just open a new issue.

**Closed by agarny** 2018-12-18 21:54 UTC
