### ISSUE TITLE
Unexpected simulation behaviour with CVODE and LR 1991

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#648] opened 2015-06-15 21:25 UTC
Trying to run the Luo-Rdy 1991 model (https://models.physiomeproject.org/workspace/luo_rudy_1991) I'm finding some strange things happening. Using the default settings, I can see the stimulus current pulse but no response in membrane potential.

![screen shot 2015-06-16 at 9 21 12 am](https://cloud.githubusercontent.com/assets/811244/8171043/14d43164-1409-11e5-974e-dc86a38c8e74.png)

When I change the point interval to 0.1 I get the same results.

However, when I now change the CVODE max step to 0.1 I get the expected action potential

![screen shot 2015-06-16 at 9 21 12 am](https://cloud.githubusercontent.com/assets/811244/8171062/4229d77c-1409-11e5-895e-268078a4d8ea.png)

I would have expected changing the point interval would have accomplished the same?

I'm also not sure why having a larger time step the stimulus current gets resolved but there is no action potential? This behaviour continues if I run the simulation for the full 9000 pacing period.

This is using OpenCOR 0.4.1.

**Comment by mirams** [comment] 2015-06-15 21:41
By default CVODE will interpolate output to the requested point interval, it doesn't bother solving at that resolution if it doesn't think it has to, to stay within tolerances. If you switch off the "Interpolate" option (#371) that should give the expected behaviour.

I guess the stimulus current is returned by a different method than the ODE solve itself - what we call derived quantities, so that will be explicitly calculated at each output point, regardless of CVODE max step.

**Comment by nickerso** [comment] 2015-06-16 03:23
I guess its really more the behaviour I expect :) generally, if the stimulus current is being successfully resolved, then I'd expect to see an action potential. It gets a bit confusing to me when different variables in the same model are being evaluated at different times...especially as in this particular case as the solution of the differential equations is clearly incorrect (in my way of looking at this!).

**Comment by agarny** [comment] 2015-06-16 08:57
As you know, the stimulus current is computed using a simple algebraic equation, so CVODE doesn't know anything about it (unlike for the transmembrane potential). So, keeping in mind what @mirams said, what you got in the first place is completely 'normal'.

@mirams suggested a way to get the 'correct' result by setting ```Interpolate solution``` to ```False```. Another is by setting ```Maximum step``` to the duration of the stimulus. @mirams' suggestion is very convenient, but it is more time consuming to compute. For example, in the case of the LR1 model, to set ```Maximum step``` to ```2``` (milliseconds) will give a 20% decrease in computational time compared with setting ```Interpolate solution``` to ```False```. Still, I hadn't thought about @mirams' suggestion and I should update the documentation accordingly (the documentation already mentioned setting ```Maximum step``` to the duration of the stimulus).

Anyway, closing since it's all 'normal'... :)

**Closed by agarny** 2015-06-16 08:57 UTC

**Comment by nickerso** [comment] 2015-06-16 22:35
> As you know, the stimulus current is computed using a simple algebraic equation, so CVODE doesn't know anything about it (unlike for the transmembrane potential). So, keeping in mind what @mirams said, what you got in the first place is completely 'normal'.

Why does CVODE not know anything about it? Are those algebraic variables in the model not being updated while integrating over a time period? Since a rate depends on this algebraic variable it should be part of the integrator RHS routine (i.e., the compute rates function from CCGS) and I should be seeing that variable plotted not an independent variable updated outside the integration.

The problem I have is that when I plot IStim I am not getting the actual IStim that is used in the integration. When I'm debugging issues like this in my models, I first look to make sure IStim is being correctly detected - and in OpenCOR, it looks to me as if it is while in actual fact it is not. Seeing that it appears to be correctly resolved in the simulation, I would then normally assume that my time stepping is not a problem, which is an incorrect assumption in this case. 

I have to admit that I am now quite curious as to how you are using CVODE in OpenCOR :) Are you simply performing one integration from starting point to ending point or do you perform a series of integrations of size point interval until you get to the ending point? In my own code, I always set the actual maximum step size used to max(point interval, max step size given) and then there is no need for any interpolation...

**Comment by agarny** [comment] 2015-06-17 08:46
> Why does CVODE not know anything about it? Are those algebraic variables in the model not being updated while integrating over a time period? Since a rate depends on this algebraic variable it should be part of the integrator RHS routine (i.e., the compute rates function from CCGS) and I should be seeing that variable plotted not an independent variable updated outside the integration.

They are, they are. I just meant that CVODE doesn't take those algebraic variables into account when deciding on what step to use, etc. At least, not directly. As we know, they can be indirectly taken into account, as is the case with the stimulus current since it is used to compute dV/dt. Sorry for the confusion.

> The problem I have is that when I plot IStim I am not getting the actual IStim that is used in the integration. When I'm debugging issues like this in my models, I first look to make sure IStim is being correctly detected - and in OpenCOR, it looks to me as if it is while in actual fact it is not. Seeing that it appears to be correctly resolved in the simulation, I would then normally assume that my time stepping is not a problem, which is an incorrect assumption in this case.

The IStim you plot gets its value from what is computed when executing the code generated by ```CodeInformation::ratesString()```, which is the code executed by CVODE to compute the RHS of the model. So, CVODE clearly detects IStim, as shown by your first screenshot (and by my own tests).

Now, by default and as @mirams said, CVODE interpolates the solution and that's where the 'problem' lies since it clearly doesn't work with the LR91 model (and, in fact, with most models that require a stimulus protocol). Personally, I have decided to do what CVODE does by default. I believe this is the right thing to do since OpenCOR/CellML can be used to solve any system of ODEs. It's just that people should be aware that CVODE's default way of doing things may not be suitable for the type of model they want to use, as documented in the CVODE (and IDA) documentation that comes with OpenCOR.

> I have to admit that I am now quite curious as to how you are using CVODE in OpenCOR :) Are you simply performing one integration from starting point to ending point or do you perform a series of integrations of size point interval until you get to the ending point? In my own code, I always set the actual maximum step size used to max(point interval, max step size given) and then there is no need for any interpolation...

OpenCOR makes one calls to [```CVode()```](https://github.com/opencor/opencor/blob/0.4/src/plugins/solver/CVODESolver/src/cvodesolver.cpp#L248) to go from ```P1``` to ```P2``` with ```P2-P1 = Point interval```. So, to go from ```Starting point``` to ```Ending point```, there will be a series of calls to [```CVode()```](https://github.com/opencor/opencor/blob/0.4/src/plugins/solver/CVODESolver/src/cvodesolver.cpp#L248) of size ```Point interval```.

From what I can tell, you are doing something similar (see [here](https://github.com/nickerso/csim-v2/blob/master/examples/cvode-integrator/cvode-integrator.cpp#L130)). However, I can see that you also make a call to ```CVodeSetStopTime()```, which effectively disables the interpolation. In OpenCOR, we only make that call (as seen [here](https://github.com/opencor/opencor/blob/0.4/src/plugins/solver/CVODESolver/src/cvodesolver.cpp#L246)) when the user does **not** want the solution to be interpolated.

As mentioned elsewhere, to interpolate the solution means that we get the solution (much) faster, but it also means that it may not work under certain circumstances (such as models that require a stimulus protocol).

So, I guess the question is whether we want to always call ```CVodeSetStopTime()``` before calling ```CVode()``` (as csim/csim-2 does) or whether we want to call it only when requested by the user (as OpenCOR does)? Another alternative to calling ```CVodeSetStopTime()``` for a model with a stimulus protocol is to set ```Maximum step``` to the length of the stimulus. As mentioned in my previous message, this will not only give the expected result, but it will also do so faster than if we were to call ```CVodeSetStopTime()```.
