### ISSUE TITLE
Code generation with custom XML

### ISSUE THREAD

**Issue by gbernardino** [opencor/opencor#2701] opened 2022-11-07 22:12 UTC
I was using an adapted XMLfile  to export Cell-ML to [Cython](https://cython.org/). In previous versions, it was able to select the XML used to generate the Tools/cellML File Export To, but in the new version, the options seem fixed. Is it possible to register an XML specifying the translations?

Thanks

PS:  Maybe this is more of a libcellml question, but when exporting a CellML 1.1, if I import the same component several times, their variables/states end up having the same names and it is difficult to differentiate them. A workaround I use is to export to CellML 1.0, since it also allows me to see the variables in the Simulation tab when working with OpenCOR, but is there a cleaner solution?

**Comment by agarny** [comment] 2022-11-07 23:47
> I was using an adapted XMLfile to export Cell-ML to [Cython](https://cython.org/). In previous versions, it was able to select the XML used to generate the Tools/cellML File Export To, but in the new version, the options seem fixed. Is it possible to register an XML specifying the translations?

Argh, yes, that "feature" was removed. We wanted to make the UI a bit easier to use when it comes to exporting a CellML file to another format.

Also, OpenCOR (currently) uses the legacy CellML API, which does indeed allow the export of a CellML file using an XML-based description. With OpenCOR 0.6 and below, we provided the XML file for different formats and people, like yourself, could indeed create and use their own XML description to export a CellML file to a given format.

However, OpenCOR will, eventually, use [libCellML](https://libcellml.org/) and that "feature" is not present. libCellML can currently export a CellML file to C and Python, and you can customise the export through the API (see https://libcellml.org/documentation/v0.2.0/api/classlibcellml_1_1GeneratorProfile). So, you should be able to mimic what you did before by using libCellML.

This being all said, if you want to use CellML from Python, you can do this using the current OpenCOR snapshot (see https://opencor.github.io/user/pythonSupport.html). As it happens, OpenCOR 0.7 will be the first version of OpenCOR with Python support. It's not perfect because our current approach relies on a specific version of Python (3.7.5 in our case) being shipped with OpenCOR. This is clearly not ideal, but it works. It's just that with OpenCOR 0.8, we will be using [libOpenCOR](https://opencor.ws/libopencor/), OpenCOR's new backend library, which has "proper" Python bindings. So, in the long term, people will be able to use libOpenCOR's Python bindings.

> PS: Maybe this is more of a libcellml question, but when exporting a CellML 1.1, if I import the same component several times, their variables/states end up having the same names and it is difficult to differentiate them. A workaround I use is to export to CellML 1.0, since it also allows me to see the variables in the Simulation tab when working with OpenCOR, but is there a cleaner solution?

Where do you see that "their variables/states end up having the same names"? In the Simulation Experiment view in OpenCOR?

**Comment by gbernardino** [comment] 2022-11-08 20:27
Thanks Alan for the reply! I answer below

> > I was using an adapted XMLfile to export Cell-ML to [Cython](https://cython.org/). In previous versions, it was able to select the XML used to generate the Tools/cellML File Export To, but in the new version, the options seem fixed. Is it possible to register an XML specifying the translations?
> 
> Argh, yes, that "feature" was removed. We wanted to make the UI a bit easier to use when it comes to exporting a CellML file to another format.
> 
> Also, OpenCOR (currently) uses the legacy CellML API, which does indeed allow the export of a CellML file using an XML-based description. With OpenCOR 0.6 and below, we provided the XML file for different formats and people, like yourself, could indeed create and use their own XML description to export a CellML file to a given format.
> 
> However, OpenCOR will, eventually, use [libCellML](https://libcellml.org/) and that "feature" is not present. libCellML can currently export a CellML file to C and Python, and you can customise the export through the API (see https://libcellml.org/documentation/v0.2.0/api/classlibcellml_1_1GeneratorProfile). So, you should be able to mimic what you did before by using libCellML.

Thanks, I will take a look. Just to confirm, I will need to set all the mappings "by hand", there is no option to load the XML there,  right?
> 
> This being all said, if you want to use CellML from Python, you can do this using the current OpenCOR snapshot (see https://opencor.github.io/user/pythonSupport.html). As it happens, OpenCOR 0.7 will be the first version of OpenCOR with Python support. It's not perfect because our current approach relies on a specific version of Python (3.7.5 in our case) being shipped with OpenCOR. This is clearly not ideal, but it works. It's just that with OpenCOR 0.8, we will be using [libOpenCOR](https://opencor.ws/libopencor/), OpenCOR's new backend library, which has "proper" Python bindings. So, in the long term, people will be able to use libOpenCOR's Python bindings.

Really looking forward for a libopencor library that I can call from Python. In my application, I need to call simulations several times (I need to personalise, and model some longitudinal changes of the parameters), that currently I do by exporting the math from CellML and running an external solver, being able to access openCOR functionalities from Python will make my life easier. 

Also, FYI, in the latest snapshot version,I noticed that in the scripts launching jupyter, pip etc in Contents/Frameworks/Python/bin have your build's python path (#!/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3). It works after changing the path manually,

> 
> > PS: Maybe this is more of a libcellml question, but when exporting a CellML 1.1, if I import the same component several times, their variables/states end up having the same names and it is difficult to differentiate them. A workaround I use is to export to CellML 1.0, since it also allows me to see the variables in the Simulation tab when working with OpenCOR, but is there a cleaner solution?
> 
> Where do you see that "their variables/states end up having the same names"? In the Simulation Experiment view in OpenCOR?

When exporting to C/python. For instance, if you get the model of Korakianitis and Shi 2006 (https://models.physiomeproject.org/exposure/c49d416ae3a5132882e6ea7479ba50f5), it has many components of type TempRLC (which is a Windkessel) instanciated to represent different vessels (for instance Sas = systemic aortic sinus). When you export to C (in CellML 1.1, there are several states named "Pi in component TempRLC", but they get the name for the specific component instantiation when you export from CellML 1.0 (Pi in component Sas).

What I was referring to the Simulation Experiment view is that it only gets the variables defined at the higher level file (modelMain.cellml), in the korakianitis example, I can only plot the t variable. After exporting to CellML 1.0, you can find all variables.

**Comment by agarny** [comment] 2022-11-08 22:18
> Thanks, I will take a look. Just to confirm, I will need to set all the mappings "by hand", there is no option to load the XML there, right?

If you are thinking of using libCellML directly then keep in mind that it only works with CellML 2.0 at the moment. We are currently working on making it possible to load CellML 1.0/1.1 models, but we are not quite there yet (see https://github.com/cellml/libcellml/pull/982).

So, at this stage, you would first need to convert all your CellML files to CellML 2.0, which you can currently do "manually" using https://libcellml.org/services/import.

This done, if you have a CellML file that imports other CellML files, then you will need to flatten it before you can generate code for it (see this [test](https://github.com/cellml/libcellml/blob/v0.3.104/tests/importer/model_flattening.cpp#L710-L746) for instance).

> Really looking forward for a libopencor library that I can call from Python. In my application, I need to call simulations several times (I need to personalise, and model some longitudinal changes of the parameters), that currently I do by exporting the math from CellML and running an external solver, being able to access openCOR functionalities from Python will make my life easier.

You can already do this using OpenCOR's current Python bindings. We have several students/researchers who already do that at our place.

> Also, FYI, in the latest snapshot version,I noticed that in the scripts launching jupyter, pip etc in Contents/Frameworks/Python/bin have your build's python path (#!/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3). It works after changing the path manually,

Argh, we have had that problem before. Hmm, I clearly need to have another look at it. Would you mind creating an issue for it, referencing the snapshot version? Thanks in advance.

> > > PS: Maybe this is more of a libcellml question, but when exporting a CellML 1.1, if I import the same component several times, their variables/states end up having the same names and it is difficult to differentiate them. A workaround I use is to export to CellML 1.0, since it also allows me to see the variables in the Simulation tab when working with OpenCOR, but is there a cleaner solution?
> > 
> > 
> > Where do you see that "their variables/states end up having the same names"? In the Simulation Experiment view in OpenCOR?
> 
> When exporting to C/python. For instance, if you get the model of Korakianitis and Shi 2006 (https://models.physiomeproject.org/exposure/c49d416ae3a5132882e6ea7479ba50f5), it has many components of type TempRLC (which is a Windkessel) instanciated to represent different vessels (for instance Sas = systemic aortic sinus). When you export to C (in CellML 1.1, there are several states named "Pi in component TempRLC", but they get the name for the specific component instantiation when you export from CellML 1.0 (Pi in component Sas).

I can confirm the issue and that's due to our legacy CellML API, so unfortunately this won't be fixed since we are now focussing on libCellML. At least, using libCellML, that problem shouldn't occur since we generate code with the full provenance of a variable. For instance, this is what we would have for the Hodgkin-Huxley 1952 model: [`.c`](https://github.com/cellml/libcellml/blob/v0.3.104/tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.c) and [`.h`](https://github.com/cellml/libcellml/blob/v0.3.104/tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.h) files, and [`.py`](https://github.com/cellml/libcellml/blob/v0.3.104/tests/resources/generator/hodgkin_huxley_squid_axon_model_1952/model.py) file.

> What I was referring to the Simulation Experiment view is that it only gets the variables defined at the higher level file (modelMain.cellml), in the korakianitis example, I can only plot the t variable. After exporting to CellML 1.0, you can find all variables.

Yes, that's normal. The idea of having model `M` importing models `A` and `B` is that the variables in `A` and `B` are "hidden" from the user interface. If you want to see a particular variable from `A` in the user interface then you need to propagate it in model `M`.

**Comment by agarny** [comment] 2022-11-08 23:01
> > Also, FYI, in the latest snapshot version,I noticed that in the scripts launching jupyter, pip etc in Contents/Frameworks/Python/bin have your build's python path (#!/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3). It works after changing the path manually,
> 
> Argh, we have had that problem before. Hmm, I clearly need to have another look at it. Would you mind creating an issue for it, referencing the snapshot version? Thanks in advance.

Oops, I just had a look at the snapshot and everything is actually as expected. When we package OpenCOR, we obviously can't tell where OpenCOR will be deployed on a user's computer. This is why we (re)set the shebangs whenever we run a Python script. For instance, say that you want to start the Jupyter Lab, then you will do something like:
```bash
$ cd [OpenCOR]
$ ./jupyterlab
```
That script will run `[OpenCOR]/OpenCOR.app/Contents/Frameworks/Python/bin/runjupyter` and one of the things it does is to call `[OpenCOR]/OpenCOR.app/Contents/Frameworks/Python/bin/set_python_path.py` which will "fix" the shebangs.

Indeed, if you unzip OpenCOR's latest snapshot in say `~/Desktop/OpenCOR-2022-05-31-macOS` then the shebang will be `#!/Users/Alan/Work/Programming/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3`:
```bash
$ cat ~/Desktop/OpenCOR-2022-05-31-macOS/OpenCOR.app/Contents/Frameworks/Python/bin/jupyter
#!/Users/Alan/Work/Programming/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3 -s
# -*- coding: utf-8 -*-
import re
import sys
from jupyter_core.command import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
Then, if you run the `jupyterlab` script or even OpenCOR itself then the shebang will become `#!/Users/Alan/Desktop/OpenCOR-2022-05-31-macOS/OpenCOR.app/Contents/Frameworks/Python/bin/python3`:
```bash
$ cat ~/Desktop/OpenCOR-2022-05-31-macOS/OpenCOR.app/Contents/Frameworks/Python/bin/jupyter
#!/Users/Alan/Desktop/OpenCOR-2022-05-31-macOS/OpenCOR.app/Contents/Frameworks/Python/bin/python3 -s
# -*- coding: utf-8 -*-
import re
import sys
from jupyter_core.command import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
So, it's all good and there is no need for you to create an issue for it.

**Comment by gbernardino** [comment] 2022-11-09 08:52
Oh, sorry, I didn't see the runjupyter scripts.  However, it doesn't work completely for me: I still get some errors after running runjupyter, I get an error cause even if the path on jupyter was correctly changed, the python path for pip3.7/pip is not updated. Here is the output I get from runjupyter

```
(base) gbernardino@poblenou-129-22 ~ % /Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/runjupyter ; exit;
Traceback (most recent call last):
  File "/Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/set_python_path.py", line 247, in <module>
    if not update_paths(args.path, args.scripts_dir, args.clear_args, args.extra_args):
  File "/Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/set_python_path.py", line 213, in update_paths
    update_scripts(scripts_dir, new_path, clear_args, extra_args)
  File "/Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/set_python_path.py", line 125, in update_scripts
    update_script(os.path.join(bin_dir, fn), new_path, clear_args, extra_args)
  File "/Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/set_python_path.py", line 118, in update_script
    with open(script_filename, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/pip3.7'
/Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/runjupyter: /Applications/OpenCOR/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/jupyter: /Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3: bad interpreter: No such file or directory
```

Could it be possible to automatically run these scripts on the first execution / after installation? I tried to use pip from the Ipython embedded in openCOR just after installation, and it didn't work out of the box.

Thanks!

**Comment by gbernardino** [comment] 2022-11-09 11:59
Yes, that's what I tried at the very beginning and got an error. I attach a screenshot of what I tried in the Python Console of OpenCOR. 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/6797235/200822220-437f2492-8882-449c-8df2-e4865c072d8e.png">

I tried also in an unzipped version, and got similar thing (I guess that the ugly /private/var/folders... is somewhere were mac stores app content that is not in the /Applications folders)
<img width="714" alt="image" src="https://user-images.githubusercontent.com/6797235/200824598-8cfda8e4-9a82-43f1-870a-8e596e760387.png">

**Comment by agarny** [comment] 2022-11-09 22:23
Ok, I have just tried the latest snapshot on a vanilla copy of macOS 13 (Ventura) and:
 - I can confirm that things work fine if I use the ZIP file:
 ![Using ZIP file](https://user-images.githubusercontent.com/602265/200951899-72f7febf-bc50-4de7-93f9-10b09ec9cae4.png)
 - But NOT if I use the installer:
 ![Using installer](https://user-images.githubusercontent.com/602265/200951947-eb0cffd9-248f-4fa3-b70f-2a24479fee14.png)
I had the gut feeling that it might have had something to do with macOS preventing everybody and everything from accessing and modifying files by default. And, indeed, if you follow the instructions at https://support.apple.com/en-nz/guide/mac-help/mchlp1203/mac and change the privileges for `everyone` from `Read only` to `Read & Write` for `/Applications/OpenCOR` and have it applied to enclosed items (or simply run `sudo chmod -R 757 *` in `/Applications/OpenCOR`) then you will be fine:
![Using installer #2](https://user-images.githubusercontent.com/602265/200954625-6e217fe3-65fc-495a-98c0-fdc1d7d6a754.png)
I am not sure there is much we can do about it, except to add this to our documentation, which I am going to do. By default, it looks like it's easier to just use the ZIP file. However, in your case, I really wonder why you did to get that `/private/var/folders/...` folder!

**Comment by gbernardino** [comment] 2022-11-10 08:54
Apparently, you can put [shebang paths relative to the script path](https://stackoverflow.com/questions/20095351/shebang-use-interpreter-relative-to-the-script-path). I tried it, and it worked. Could it be possible to use that as a quickfix? I guess that the cleaner solution would be to set the paths during installation. The code below (from stackoverflow) links to the python in the same folder:

`#!/usr/bin/perl -e$_=$ARGV[0];exec(s/\w+$/python/r,$_)`

I have absolutely no clue what is the /private/var (maybe my configuration broke for having to OpenCORs?). I am using the installed version of opencor. For me, we can close the issue.

Thanks for all the help!

**Comment by agarny** [comment] 2022-11-10 10:01
> Apparently, you can put [shebang paths relative to the script path](https://stackoverflow.com/questions/20095351/shebang-use-interpreter-relative-to-the-script-path). I tried it, and it worked. Could it be possible to use that as a quickfix? I guess that the cleaner solution would be to set the paths during installation. The code below (from stackoverflow) links to the python in the same folder:

Remember, we have installers for OpenCOR on Windows and macOS, but also a ZIP file, and a tarball file on Linux. So, we can't fix those paths during "installation" when using a ZIP / tarball file.

> `#!/usr/bin/perl -e$_=$ARGV[0];exec(s/\w+$/python/r,$_)`

This works on Linux / macOS, but not on Windows, unfortunately.

> I have absolutely no clue what is the /private/var (maybe my configuration broke for having to OpenCORs?). I am using the installed version of opencor. For me, we can close the issue.

I am going to keep it open for now, at least until I have updated the documentation since we need to be consistent across the different platforms that we support.

> Thanks for all the help!

You are most welcome. Hopefully, things will be a lot smoother when we have libOpenCOR!

**Comment by gbernardino** [comment] 2022-11-10 19:32
And what about adding a system dependent option while generating the installer/redistributables? While executing a python script, it can detect in which os it is running, and depending on that either do nothing or change the shebang of those files.

**Comment by agarny** [comment] 2022-11-10 21:36
> And what about adding a system dependent option while generating the installer/redistributables? While executing a python script, it can detect in which os it is running, and depending on that either do nothing or change the shebang of those files.

Sorry, I am not sure I understand what you are suggesting.

Also, we have something that has, overall, been working fine (albeit I need to update the documentation for the case where OpenCOR is installed using the installer and the OS doesn't, by default, allow to overwrite files), not to mention that we are going to replace that Python bindings with libOpenCOR, so not sure it's worth spending more time on this.

**Comment by gbernardino** [comment] 2022-11-11 08:48
I was thinking of a Python script to be executed during the generation of the redistributables that does something like
`if plattform.plattform() == "osx":
       changeSHebangs()
`

**Comment by dbrnz** [comment] 2022-11-11 09:02
> if plattform.plattform() == "osx": changeSHebangs() 

To what?

**Comment by gbernardino** [comment] 2022-11-11 09:14
Change the shebangs of the python scripts (pip, jupyter, etc) to
`    #!/usr/bin/perl -e$_=$ARGV[0];exec(s/\w+$/python/r,$_)`
which looks at the python binary in the same folder of the script  (see comment above)

**Comment by agarny** [comment] 2022-11-11 19:47
> Change the shebangs of the python scripts (pip, jupyter, etc) to ` #!/usr/bin/perl -e$_=$ARGV[0];exec(s/\w+$/python/r,$_)` which looks at the python binary in the same folder of the script (see comment above)

To change the shebangs at the packaging stage is not a problem, but again what about Windows? Windows doesn't come with Perl by default. As much as possible, I would like a solution that works across our three supported platforms.

I tried to look for such a cross-platform solution to our shebang issue, but I couldn't find any. Maybe it just can't be done on Windows?

I have just checked the installer on Windows, and we can use our Python scripits without any problem (i.e. unlike macOS, Windows doesn't, by default, prevent "properly" installed applications from modiifying files).

So, since your approach will definitely help with our OpenCOR installer on macOS, I am going to implement it, as well as on Linux (it won't harm!). I have therefore created an issue for it (see issue #2705) and closing this one.

**Closed by agarny** 2022-11-11 19:47 UTC
