### ISSUE TITLE
SED-ML file is unreadable.

### ISSUE THREAD

**Issue by Jasmine969** [opencor/opencor#2734] opened 2023-08-26 06:12 UTC
I exported a SED-ML file by clicking the sedmlLogo button in the Simulation view. When I reopen OpenCOR, how can I load the SED-ML file? When I used File - Open to open this exported SED-ML file, it says 
> "The Simulation Experiment view requires a valid simulation environment to work. 
(See helow for more information.) 
[1:1] Error: file unreadable." 
![image](https://github.com/opencor/opencor/assets/64536863/a127c33a-2ff1-4aca-99d7-9efae5f724bf)

**Comment by agarny** [comment] 2023-08-26 06:44
Hi, thanks for the report. This is clearly not the expected behaviour. May I ask which version of OpenCOR you are using? Otherwise, considering the message, I am wondering whether it might not be due to the file path containing a Chinese character? I would expect things to work since the framework ([Qt](https://www.qt.io/product/framework)) used by OpenCOR supports such characters, but then again I am not sure that's something I have ever tried. Anyway, just in case, make sure to use the [latest version of OpenCOR](https://opencor.ws/downloads/index.html) (0.7.1).

**Comment by agarny** [comment] 2023-08-26 06:54
Ok, it's not the Chinese characters in the file path. I have just opened a CellML file from a folder with a Chinese characters in it, created a SED-ML file from it, opened the SED-ML file and everything is fine.
<img width="1852" alt="Screenshot 2023-08-26 at 18 52 03" src="https://github.com/opencor/opencor/assets/602265/f9b9a012-2fc4-4670-bb40-d182ae73cd8d">

**Comment by Jasmine969** [comment] 2023-08-26 06:58
thx a lot for your in-time response. it's indeed owing to the Chinese character!

**Comment by agarny** [comment] 2023-08-26 23:57
> thx a lot for your in-time response. it's indeed owing to the Chinese character!

Hmm, this is still strange since I tried with some Chinese characters (see above) and it was fine. Then again, the operating system itself is in English, so maybe that's the difference if yours is in Chinese. I will try with my operating system in Chinese this coming week to get confirmation.

**Comment by agarny** [comment] 2023-08-28 03:37
Ok, I have just tested OpenCOR on a Chinese-based machine and... I am indeed experiencing your issue if the file path contains some Chinese characters while I don't if the file path only contains characters from the alphabet. This clearly has to do with the system being in Chinese since it works in both cases on an English-based machine. 
![Image1](https://github.com/opencor/opencor/assets/602265/b46c95cf-08e7-4f91-9a9c-2c028d8682a1)
![Image2](https://github.com/opencor/opencor/assets/602265/8f5597ba-9441-49a8-9ba2-cf36fa744cf1)
I now need to debug OpenCOR itself to see whether this is something that can be fixed.

**Comment by agarny** [comment] 2023-08-28 06:35
> This clearly has to do with the system being in Chinese since it works in both cases on an English-based machine.

I have to revise that comment of mine since the English-based machine I tested was running macOS while just above I was running Windows. And, indeed, when I use an English-based Windows machine, I am getting the same behaviour as on the Chinese-based Windows machine (and not the same behaviour as on the English-based macOS machine)!

**Comment by dbrnz** [comment] 2023-08-28 07:06
Could it be that MS Windows is not 100% Unicode?

**Comment by agarny** [comment] 2023-08-28 07:44
> Could it be that MS Windows is not 100% Unicode?

I would expect Windows to be 100% Unicode, but who knows...!? However, the encoding might be different.

Anyway, I believe I have got to the bottom of it. When it comes to reading a SED-ML, we use a third-party library ([libSEDML](https://github.com/fbergmann/libSEDML)) and it can read some SED-ML either from a SED-ML file (by giving it the file path to a SED-ML file) or from a string.

OpenCOR uses the former approach and this is where the problem lies: libSEDML doesn't seem to handle file name with Unicode characters in them. I confirmed this by having OpenCOR to read the file contents and then ask libSEDML to interprete it, and it's all fine.

Now, because there is a workaround to this problem (i.e. not use a file path with Unicode characters!), I am not going to fix it in the current version of OpenCOR, not least OpenCOR's SED-ML support is being moved to libOpenCOR and that libOpenCOR is going to be used by OpenCOR at some point.

libOpenCOR already asks libSEDML to read some SED-ML from a string, so we are good in that respect. However, to read (using pure C++, no Qt) a file which path contains some Unicode characters requires a modern C++ standard (C++17). For my own record, here is some code to read the contents of such a file:
```c++
#include <filesystem>
#include <fstream>

int main()
{
    auto filePath = std::filesystem::u8path("C:\\Users\\Alan\\Desktop\\新建文件夹\\noble_model_1962.sedml");
    std::ifstream file(filePath, std::ios_base::binary);

    if (!file.is_open()) {
        printf("Can't open the file!\n");
    } else {
        const auto fileSize = std::filesystem::file_size(filePath);
        std::vector<char> contents(fileSize + 1);

        file.read(reinterpret_cast<char *>(&contents[0]), static_cast<std::streamsize>(fileSize));

        contents[fileSize] = '\0';

        printf("---[FILE CONTENTS]---\n");
        printf("%s\n", reinterpret_cast<char *>(&contents[0]));
        printf("---------------------\n");
    }

    return 0;
}
```
This is not the approach (to reading a file) currently used by libOpenCOR, so I am going to modify that and add some tests to ensure that everything works as expected (see https://github.com/opencor/libopencor/issues/242). So, closing this issue as a result.

**Closed by agarny** 2023-08-28 07:44 UTC
