### ISSUE TITLE
Can't install python package that uses wheels

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2442] opened 2021-03-18 20:28 UTC
When trying to install cvxpy via 

`!pip install cvxpy`

in the opencor pythonshell in Ubuntu_20, the following error occurs.

> ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly

**Comment by agarny** [comment] 2021-03-18 20:34
@dbrnz, I am getting the feeling that there might not be much we can do about this. Would you agree? (One more reason for coming up with libOpenCOR... :/)

**Comment by dbrnz** [comment] 2021-03-18 21:48
The way to install it would be in a shell outside of OpenCOR but using OpenCOR's Python:
```
$ /path/to/OpenCOR/Python/bin/python -m pip install cvxpy
```
I suspect the failure is because of a missing `cvxpy` dependency.

**Comment by agarny** [comment] 2021-03-18 21:53
Thanks @dbrnz. I imagine that @FinbarArgus tried to install `cvxpy` using OpenCOR's Python console window since he mentions `!pip` rather than `pip`? So, why would that be different from installing `cvxpy` from "a shell outside of OpenCOR but using OpenCOR's Python"?

**Comment by FinbarArgus** [comment] 2021-03-18 22:05
Thanks @dbrnz and @agarny. Doing 
`
$ /path/to/OpenCOR/Python/bin/python -m pip install cvxpy`

gives the same error.

**Comment by dbrnz** [comment] 2021-03-18 22:35
@FinbarArgus what shows in the error log? Have you seen https://github.com/cvxgrp/cvxpy/issues/1017??


@agarny 
> would that be different from installing cvxpy from "a shell outside of OpenCOR but using OpenCOR's Python"?

As such nothing except maybe a chance to see what else might be going on. There is nothing special about OpenCOR's Python and if `pip install cvxpy` fails for OpenCOR I would expect it to fail for the same reason if the system Python was used.

**Comment by dbrnz** [comment] 2021-03-18 22:51
Oops, @FinbarArgus I meant this issue https://github.com/cvxgrp/cvxpy/issues/1126 for `cvxpy`...

**Comment by agarny** [comment] 2021-03-18 22:54
> > would that be different from installing cvxpy from "a shell outside of OpenCOR but using OpenCOR's Python"?
> 
> As such nothing except maybe a chance to see what else might be going on. There is nothing special about OpenCOR's Python and if `pip install cvxpy` fails for OpenCOR I would expect it to fail for the same reason if the system Python was used.

Thanks for the confirmation @dbrnz.

**Comment by FinbarArgus** [comment] 2021-03-18 23:23
[log.txt](https://github.com/opencor/opencor/files/6167689/log.txt)

**Comment by agarny** [comment] 2021-03-18 23:57
@FinbarArgus, it's purely a problem with [`cvxpy`](https://github.com/cvxgrp/cvxpy). The problem is [here](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/cvxcore/src/LinOpOperations.cpp#L393), i.e. can't compile `assert(arg_idx <= lin.get_args().get_shape());` and indeed `get_args()` is defined [here](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/cvxcore/src/LinOp.hpp#L73) and you can't call `get_shape()` on it. I would say that this line simply cannot be built, so I wonder why it's there...!?

Anyway, it's only an assertion, which is only useful when building a debug version of `cvxpy`. So, that line can be commented out. However, I have no idea where `cvxpy/cvxcore/src/LinOpOperations.cpp` is located on my/your system, so can't test my suggestion locally...!?

**Comment by FinbarArgus** [comment] 2021-03-19 00:38
Fantastic! I downloaded the cvxpy source files from here `https://pypi.org/project/cvxpy/#modal-close`, commented out `assert(arg_idx <= lin.get_args().get_shape());` in `cvxpy/cvxcore/src/LinOpOperations.cpp` and installed with '$ /path/to/OpenCOR/Python/bin/python -m pip install -e .' in the cvxpy directory and all seems to be working!

Thank you!! :D

**Comment by agarny** [comment] 2021-03-19 01:45
Great, glad that you managed to install `cvxpy`. Closing this issue then.

**Closed by agarny** 2021-03-19 01:45 UTC
