### ISSUE TITLE
Model works in Linux but not in Windows

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2818] opened 2024-11-14 03:26 UTC
This model 

[parasymp_CVS_windows_fail.zip](https://github.com/user-attachments/files/17742411/parasymp_CVS_windows_fail.zip)

Works on linux but not on Windows. On windows (OpenCOR_0.7.1) The model solver fails.

Solver params:
start_time = 0.0
end_time = 10.0
dt = 0.0001
maximumTimeStep = 0.0001
maximumNumberOfSteps = 5000
All other params set to default.

The solver seems to behave differently in Windows and Linux.

**Comment by agarny** [comment] 2024-11-14 04:55
Hi @FinbarArgus, I can confirm the issue, but I am not sure there is much we can do about it.

All OpenCOR does is to instantiate and customise the CVODE solver based on the information provided by the user. And, as you can imagine, this is done using the exact same code whether you are on Windows or Linux. So, if anything, I would say that this is a solver issue.

FWIW, I tried your model with different solver parameters, but to no avail. On Windows, it always fails. On macOS, it gives me the impression that your model is very stiff. I, for instance, tried the Adams-Moulton integration method (normally suitable for non-stiff models while BDF is suitable for stiff models, the reason for which OpenCOR uses it by default) and it failed.

From there, I tried with Forward Euler. Normally, if your model is solvable then you should be able to use Forward Euler even if it means using a very small time step. Well, this also failed for me.

So, yeah, not sure what to suggest here!

(I imagine that `control_parasymp_flat.cellml` was generated using libCellML? Anyway, I tried to open it in my Web and libOpenCOR based environment, but to no avail either. It's complaining about some parameters being equivalent and being both initialised...!?)

**Comment by agarny** [comment] 2024-11-14 22:48
@FinbarArgus, FWIW, I get the same flattened version of the model using the latest version of libCellML. Otherwise, when generating code with libCellML, 4 algebraic variables get computed using a non-linear algebraic system: `pulmonary_GE_module/C_O2_a`, `pulmonary_GE_module/C_CO2_a`, `terminal_venous_connection/C_O2_p_venous_ave`, and `terminal_venous_connection/C_CO2_p_venous_ave`. I am surprised that the CellML API (used by OpenCOR) doesn't do the same. Anyway, your model is very big, so it makes it difficult to check things further.

What is certain is that there is nothing wrong per se with our use of CVODE and I feel like the issue is about your model being very stiff and numerical discrepancies between operating systems. So, closing this issue for now...

**Closed by agarny** 2024-11-14 22:48 UTC
