### ISSUE TITLE
Single Cell view: error opening CellML models from SED-ML documents

### ISSUE THREAD

**Issue by nickerso** [opencor/opencor#942] opened 2016-04-18 02:32 UTC
Reporting an error I've seen on Windows but unable to replicate on OS X :)

If you load a SED-ML into OpenCOR which references a model via relative path (e.g., `../Tutorial Models/model.cellml`), this will load into OpenCOR fine and allow you to run the simulation experiment. But when you try to open the CellML model using that cool little button in the simulation view the user gets an error message about being unable to find the CellML model (with the fully resolved path being presented with good old `%20`'s encoded into it). Not sure if it is the relative path or having a space in the path that is messing things up. This works fine when trying essentially the same relative path on OS X, with the latest snapshot of OpenCOR.

**Comment by agarny** [comment] 2016-04-18 08:29
Hmm, in fact, we just can't, on Windows, open any CellML file that is referenced in a SED-ML file. Argh, sorry about that!

**Comment by nickerso** [comment] 2016-04-18 09:08
Its not all bad - if you load a SED-ML from the repository using the "launch in OpenCOR" feature, then that will let you open the remote CellML file - on windows (I've seen that working this morning).

**Comment by agarny** [comment] 2016-04-18 09:12
Well, I have found the cause of the problem, so it will be fixed for the next snapshot.

**Closed** 2016-04-18 12:54 UTC
Labels: Task, Windows
